[package]
name = "annals-usage"
version = "0.4.4"
edition.workspace = true

[dependencies]
clap = { workspace = true }
nucleus-client = { workspace = true }
nucleus-core = { workspace = true }
rusqlite = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
