#!/bin/zsh

unsetopt VERBOSE XTRACE

case "${1-}" in
    --help|-h|--version|-V|--register-usage)
        exec "$HOME/Library/Application Support/Cast/install/current/libexec/cast" "$@"
        ;;
esac

cast_state_dir=${CAST_STATE_DIR-}
usage_thread=${CODEX_THREAD_ID-}
usage_database=${CHANCERY_USAGE_DB-}
usage_disabled=${CHANCERY_USAGE_DISABLED-}
if [[ -f "${HOME:?}/.zshrc" ]]; then
    source "$HOME/.zshrc" >/dev/null 2>&1
fi
unsetopt VERBOSE XTRACE

exec 3<&0
{ print -r -- "${THEIRSTACK_API_KEY-}"; print -r -- "${BRAVE_SEARCH_API_KEY-}"; print -r -- "$cast_state_dir"; } | /usr/bin/env -i \
    HOME="$HOME" \
    CODEX_THREAD_ID="$usage_thread" \
    CHANCERY_USAGE_DB="$usage_database" \
    CHANCERY_USAGE_DISABLED="$usage_disabled" \
    PATH=/usr/bin:/bin:/usr/sbin:/sbin \
    /bin/zsh -c '
IFS= read -r THEIRSTACK_API_KEY
IFS= read -r BRAVE_SEARCH_API_KEY
IFS= read -r cast_state_dir
export THEIRSTACK_API_KEY BRAVE_SEARCH_API_KEY
if [[ -n "$cast_state_dir" ]]; then export CAST_STATE_DIR="$cast_state_dir"; fi
exec 0<&3
exec 3<&-
exec "$HOME/Library/Application Support/Cast/install/current/libexec/cast" "$@"
' cast "$@"
