#!/bin/zsh

cast_environment=(
    "HOME=${HOME:?}"
    "PATH=/usr/bin:/bin:/usr/sbin:/sbin"
    "CODEX_THREAD_ID=${CODEX_THREAD_ID-}"
    "CHANCERY_USAGE_DB=${CHANCERY_USAGE_DB-}"
    "CHANCERY_USAGE_DISABLED=${CHANCERY_USAGE_DISABLED-}"
    "CHANCERY_USAGE_INTERNAL=${CHANCERY_USAGE_INTERNAL-}"
)
if [[ -n "${CAST_STATE_DIR-}" ]]; then
    cast_environment+=("CAST_STATE_DIR=$CAST_STATE_DIR")
fi

exec /usr/bin/env -i "${cast_environment[@]}" \
    "$HOME/Library/Application Support/Cast/install/current/libexec/cast" "$@"
