#!/bin/sh

set -eu

PIPELINE_ROOT=$(CDPATH='' cd "$(dirname "$0")/.." && pwd)
export PIPELINE_ROOT
. "$PIPELINE_ROOT/pipeline/lib.sh"

generate_usage() {
    printf '%s\n' \
        'Usage: pipeline/generate.sh --check|--write [--product PRODUCT]...'
}

emit_ci_wrapper() {
    cat <<EOF
#!/bin/sh
# Generated by pipeline/generate.sh from pipeline/products/$PRODUCT_ID.sh.
# Edit the descriptor or shared runtime, then regenerate.
set -eu
PRODUCT_DIR=\$(CDPATH='' cd "\$(dirname "\$0")" && pwd)
CELL_ROOT=\$(CDPATH='' cd "\$PRODUCT_DIR/.." && pwd)
exec python3 "\$CELL_ROOT/ci_broker/client.py" run --repo-root "\$CELL_ROOT" --gate "$CI_GATE_ID" --lane "$CI_RESOURCE_CLASS" -- "\$CELL_ROOT/pipeline/ci.sh" "$PRODUCT_ID" "\$@"
EOF
}

emit_release_wrapper() {
    cat <<EOF
#!/bin/sh
# Generated by pipeline/generate.sh from pipeline/products/$PRODUCT_ID.sh.
# This publishes a release; it is not a build command.
set -eu
PRODUCT_DIR=\$(CDPATH='' cd "\$(dirname "\$0")" && pwd)
CELL_ROOT=\$(CDPATH='' cd "\$PRODUCT_DIR/.." && pwd)
exec "\$CELL_ROOT/pipeline/release.sh" "$PRODUCT_ID" "\$@"
EOF
}

generate_file() {
    output_path=$1
    output_kind=$2
    temporary_path=$(mktemp "${TMPDIR:-/tmp}/cell-pipeline-generated.XXXXXX")
    trap 'rm -f "$temporary_path"' 0 1 2 15
    case "$output_kind" in
        ci) emit_ci_wrapper >"$temporary_path" ;;
        release) emit_release_wrapper >"$temporary_path" ;;
        *) pipeline_fail "unknown generated output kind: $output_kind" ;;
    esac

    case "$generation_mode" in
        check)
            if ! cmp -s "$temporary_path" "$output_path"; then
                printf 'pipeline/generate.sh: generated file is stale: %s\n' \
                    "${output_path#"$PIPELINE_ROOT/"}" >&2
                generation_failed=1
            fi
            ;;
        write)
            chmod 755 "$temporary_path"
            mv "$temporary_path" "$output_path"
            temporary_path=
            ;;
    esac
    [ -z "$temporary_path" ] || rm -f "$temporary_path"
    trap - 0 1 2 15
}

[ "$#" -ge 1 ] || { generate_usage >&2; exit 2; }
case "$1" in
    --check) generation_mode=check ;;
    --write) generation_mode=write ;;
    *) generate_usage >&2; exit 2 ;;
esac
shift

requested_products=
while [ "$#" -gt 0 ]; do
    [ "$1" = --product ] && [ "$#" -ge 2 ] \
        || { generate_usage >&2; exit 2; }
    requested_product=$2
    case "$requested_product" in
        *[!a-z0-9-]*|'') generate_usage >&2; exit 2 ;;
    esac
    [ -f "$PIPELINE_ROOT/pipeline/products/$requested_product.sh" ] \
        || pipeline_fail "product descriptor not found: $requested_product"
    case " $requested_products " in
        *" $requested_product "*) ;;
        *) requested_products="$requested_products $requested_product" ;;
    esac
    shift 2
done
if [ -n "$requested_products" ]; then
    selected_products=$(printf '%s\n' $requested_products)
else
    selected_products=$(pipeline_products)
fi

generation_failed=0
while IFS= read -r product_id; do
    [ -n "$product_id" ] || continue
    pipeline_load_descriptor "$product_id"
    generate_file "$PIPELINE_ROOT/$PRODUCT_DIR/ci.sh" ci
    generate_file "$PIPELINE_ROOT/$PRODUCT_DIR/release.sh" release
done <<EOF
$selected_products
EOF

[ "$generation_failed" -eq 0 ] || exit 1
if [ "$generation_mode" = check ]; then
    printf '%s\n' 'pipeline/generate.sh: generated entry points are current'
else
    printf '%s\n' 'pipeline/generate.sh: generated entry points updated'
fi
