[package]
name = "weaver"
version = "0.5.2"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
cell-prompts.workspace = true
anyhow = "1"
annals-api.workspace = true
cell-install.workspace = true
cell-maintenance.workspace = true
chancery-usage.workspace = true
clap.workspace = true
fs2.workspace = true
futures-util.workspace = true
iatreion-api.workspace = true
nucleus-client.workspace = true
nucleus-core.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
time.workspace = true
tokio.workspace = true
uuid.workspace = true

[dev-dependencies]
axum.workspace = true

[lints]
workspace = true
