#!/bin/sh
# Generated by pipeline/generate.sh from pipeline/products/conversations.sh.
# Edit the descriptor or shared runtime, then regenerate.
set -eu
PRODUCT_DIR=$(CDPATH='' cd "$(dirname "$0")" && pwd)
CELL_ROOT=$(CDPATH='' cd "$PRODUCT_DIR/.." && pwd)
exec python3 "$CELL_ROOT/ci_broker/client.py" run --repo-root "$CELL_ROOT" --gate "conversations" --lane "heavy" -- "$CELL_ROOT/pipeline/ci.sh" "conversations" "$@"
