#!/bin/sh
# Generated by pipeline/generate.sh from pipeline/products/platter.sh.
# Edit the descriptor or shared runtime, then regenerate.
set -eu
PRODUCT_DIR=$(CDPATH='' cd "$(dirname "$0")" && pwd)
CELL_ROOT=$(CDPATH='' cd "$PRODUCT_DIR/.." && pwd)
flags=
while [ "$#" -gt 0 ]; do
    case "$1" in
        --verbose|--quiet-result) flags="$flags $1"; shift ;;
        *) break ;;
    esac
done
if [ "${1:-}" = --stage-candidate ]; then
    flags="$flags --verbose-receipt"
fi
# flags contains only the fixed presentation options above.
exec python3 "$CELL_ROOT/ci_broker/client.py" run $flags --repo-root "$CELL_ROOT" --gate "platter" --lane "heavy" -- "$CELL_ROOT/pipeline/ci.sh" "platter" "$@"
