[package]
name = "todo"
version = "0.1.0"
edition.workspace = true

[dependencies]
base64 = "0.22.1"
clap = { version = "4.5.46", features = ["derive"] }
nucleus-client = { git = "https://github.com/JTan2231/nucleus-rs.git", tag = "v0.2.0" }
nucleus-core = { git = "https://github.com/JTan2231/nucleus-rs.git", tag = "v0.2.0" }
rusqlite = { version = "0.37.0", features = ["bundled"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.143", features = ["raw_value"] }
thiserror = "2.0.16"
tokio = { version = "1.47.1", features = ["rt", "time"] }
toml = "1.1.4"
uuid = { version = "1.18.0", features = ["v7"] }

[dev-dependencies]
tempfile = "3.21.0"
