#!/bin/sh
# Generated by pipeline/generate.sh from pipeline/products/nucleus.sh.
# Edit the descriptor or shared runtime, then regenerate.
set -eu
PRODUCT_DIR=$(CDPATH='' cd "$(dirname "$0")" && pwd)
CELL_ROOT=$(CDPATH='' cd "$PRODUCT_DIR/.." && pwd)
export PYTHONDONTWRITEBYTECODE=1
exec python3 "$CELL_ROOT/pipeline/select_changes.py" product "nucleus" "$@"
