#!/bin/zsh

unsetopt VERBOSE XTRACE

case "${1-}" in
    --help|-h|--version|-V)
        exec "$HOME/Library/Application Support/Email/install/current/libexec/email" "$@"
        ;;
esac

case "${1-}:${2-}:${3-}:${4-}" in
    receive:--help:*|receive:-h:*|receive:--version:*|receive:-V:*|\
    receive:list:--help:*|receive:list:-h:*|receive:get:--help:*|receive:get:-h:*)
        exec "$HOME/Library/Application Support/Email/install/current/libexec/email" "$@"
        ;;
esac

if [[ -f "${HOME:?}/.zshrc" ]]; then
    source "$HOME/.zshrc" >/dev/null 2>&1
fi
unsetopt VERBOSE XTRACE

exec 3<&0
print -r -- "${RESEND_API_KEY-}" | /usr/bin/env -i \
    HOME="$HOME" \
    PATH=/usr/bin:/bin:/usr/sbin:/sbin \
    /bin/zsh -c '
IFS= read -r RESEND_API_KEY
export RESEND_API_KEY
exec 0<&3
exec 3<&-
exec "$HOME/Library/Application Support/Email/install/current/libexec/email" "$@"
' email "$@"
