PIPELINE_SCHEMA=1
PRODUCT_ID=annals
PRODUCT_NAME=Annals
PRODUCT_DIR=annals
CI_RESOURCE_CLASS=heavy
RELEASE_BRANCH=main
DEPLOY_PROFILE=custom
DEPLOY_CONFLICT_KEYS='global'
CARGO_MANIFEST=Cargo.toml
CARGO_PACKAGES='annals
annals-usage'
CARGO_OFFLINE=0
CLIPPY_KEEP_GOING=1
TEST_NO_FAIL_FAST=1
CI_SHELL_CHECKS='sh|annals/release.sh
sh|annals/packaging/launchd/annals
sh|annals/packaging/launchd/annals-usage
sh|annals/packaging/launchd/annals-user
sh|annals/packaging/launchd/annals-inbox
sh|annals/packaging/launchd/deploy-user.sh
sh|annals/packaging/launchd/install.sh
sh|annals/packaging/launchd/migrate-to-user.sh
sh|annals/packaging/launchd/provision-decisions-user.sh
sh|annals/packaging/launchd/test-frontend.sh
sh|annals/packaging/launchd/test-decisions-provision.sh
sh|annals/packaging/launchd/test-decisions-template.sh
sh|annals/packaging/launchd/test-inbox-runner.sh
sh|annals/packaging/launchd/test-migrate-to-user.sh
sh|annals/packaging/launchd/test-user-deploy.sh
sh|annals/packaging/launchd/test-user-frontend.sh
sh|annals/packaging/launchd/uninstall.sh'
CI_RUN_CHECKS='always|annals/packaging/launchd/test-frontend.sh
always|annals/packaging/launchd/test-decisions-template.sh
always|annals/packaging/launchd/test-inbox-runner.sh
darwin|annals/packaging/launchd/test-user-frontend.sh
darwin|annals/packaging/launchd/test-user-deploy.sh
darwin|annals/packaging/launchd/test-migrate-to-user.sh
darwin|annals/packaging/launchd/test-decisions-provision.sh'
CI_PLIST_CHECKS='darwin-if-tool:plutil|lint|annals/packaging/launchd/org.annals.inbox.plist
darwin-if-tool:plutil|lint|annals/packaging/launchd/org.annals.inbox.agent.plist'
CI_PROVIDER_VALIDATION_PHASE=before-rust
RELEASE_UNITS='annals|Annals|package|annals/crates/annals/Cargo.toml|annals-|1
annals-usage|Annals Usage|package|annals/crates/annals-usage/Cargo.toml|annals-usage-|0'
RELEASE_ALLOW_EXPLICIT_UNIT=1
RELEASE_USAGE='Usage: ./release.sh --patch|--minor|--major
       ./release.sh annals|annals-usage --patch|--minor|--major'
RELEASE_METADATA_NO_DEPS=0
RELEASE_BINARY_CHECKS='annals|target/release/annals|annals
annals-usage|target/release/annals-usage|annals-usage'
PROVIDERS='annals|annals|annals/chancery/annals|8
annals-usage|annals-usage|annals/chancery/annals-usage|3'
