PIPELINE_SCHEMA=1
PRODUCT_ID=annals
PRODUCT_NAME=Annals
PRODUCT_DIR=annals
STATUS_SCHEMA=1
STATUS_COMMAND=annals
STATUS_UNITS='annals/inbox|active|annals/inbox|annals.inbox.operate
annals/decisions-inbox|active|annals/decisions-inbox|annals.inbox.operate'
CI_RESOURCE_CLASS=heavy
RELEASE_BRANCH=main
DEPLOY_PROFILE=rust-install-v1
DEPLOY_CONFLICT_KEYS='global'
CARGO_MANIFEST=Cargo.toml
CARGO_PACKAGES='annals
annals-api
annals-usage'
CARGO_OFFLINE=0
CLIPPY_KEEP_GOING=1
TEST_NO_FAIL_FAST=1
CI_SHELL_CHECKS='sh|annals/release.sh'
CI_RUN_CHECKS=
CI_PLIST_CHECKS='darwin-if-tool:plutil|lint|annals/packaging/launchd/org.annals.inbox.plist
darwin-if-tool:plutil|lint|annals/packaging/launchd/org.annals.inbox.agent.plist'
CI_PROVIDER_VALIDATION_PHASE=before-rust
RELEASE_UNITS='annals|Annals|package|annals/crates/annals/Cargo.toml|annals-|1
annals-usage|Annals Usage|package|annals/crates/annals-usage/Cargo.toml|annals-usage-|0'
RELEASE_ALLOW_EXPLICIT_UNIT=1
RELEASE_COMPANION_MANIFESTS='annals|annals/crates/annals-api/Cargo.toml'
RELEASE_USAGE='Usage: ./release.sh --patch|--minor|--major
       ./release.sh annals|annals-usage --patch|--minor|--major'
RELEASE_METADATA_NO_DEPS=0
RELEASE_BINARY_CHECKS='annals|target/release/annals|annals
annals-usage|target/release/annals-usage|annals-usage
annals|target/release/annals-install|annals-install'
PROVIDERS='annals|annals|annals/chancery/annals|8
annals-usage|annals-usage|annals/chancery/annals-usage|3'
CI_BINARY_CHECKS='annals|target/release/annals|annals
annals-usage|target/release/annals-usage|annals-usage
annals|target/release/annals-install|annals-install'
