PIPELINE_SCHEMA=1
PRODUCT_ID=bazaar
PRODUCT_NAME=Bazaar
PRODUCT_DIR=infrastructure/bazaar
RELEASE_BRANCH=main
CARGO_MANIFEST=Cargo.toml
CARGO_PACKAGES=bazaar
CARGO_OFFLINE=1
CI_SHELL_CHECKS='sh|infrastructure/bazaar/release.sh'
RELEASE_UNITS='bazaar|Bazaar|package|infrastructure/bazaar/Cargo.toml|bazaar-|1'
RELEASE_BINARY_CHECKS='bazaar|target/release/bazaar|bazaar
bazaar|target/release/bazaar-install|bazaar-install'
PROVIDERS='bazaar|bazaar|infrastructure/bazaar/chancery|4'
