PIPELINE_SCHEMA=1
PRODUCT_ID=chancery
PRODUCT_NAME=Chancery
PRODUCT_DIR=chancery
CI_RESOURCE_CLASS=heavy
RELEASE_BRANCH=main
DEPLOY_PROFILE=custom
DEPLOY_CONFLICT_KEYS='global'
CARGO_MANIFEST=Cargo.toml
CARGO_PACKAGES=chancery
CARGO_OFFLINE=0
CLIPPY_KEEP_GOING=1
TEST_NO_FAIL_FAST=1
CI_SHELL_CHECKS='sh|chancery/release.sh
sh|chancery/packaging/macos/deploy-user.sh
sh|chancery/packaging/macos/test-deploy-user.sh
sh|chancery/packaging/macos/test-fixture-chancery.sh'
CI_RUN_CHECKS='darwin|chancery/packaging/macos/test-deploy-user.sh'
CI_PROVIDER_VALIDATION_PHASE=after-tests
RELEASE_UNITS='chancery|Chancery|package|chancery/crates/chancery/Cargo.toml|chancery-|1'
RELEASE_METADATA_NO_DEPS=0
RELEASE_BINARY_CHECKS='chancery|target/release/chancery|chancery'
PROVIDERS='chancery|chancery|chancery/provider|3'
