PIPELINE_SCHEMA=1
PRODUCT_ID=clew
PRODUCT_NAME=Clew
PRODUCT_DIR=clew
STATUS_SCHEMA=1
STATUS_COMMAND=clew
STATUS_UNITS='clew/ledger|on_demand||clew.application.track
clew/daily-email|active|clew/daily-email|clew.digest.email'
CI_RESOURCE_CLASS=heavy
RELEASE_BRANCH=main
DEPLOY_PROFILE=rust-install-v1
DEPLOY_CONFLICT_KEYS='product:clew
chancery-catalog'
CARGO_MANIFEST=Cargo.toml
CARGO_PACKAGES=clew
CARGO_OFFLINE=1
CI_SHELL_CHECKS='sh|clew/release.sh'
CI_RUN_CHECKS=''
CI_PROVIDER_VALIDATION_PHASE=before-rust
RELEASE_UNITS='clew|Clew|package|clew/Cargo.toml|clew-|1'
RELEASE_BINARY_CHECKS='clew|target/release/clew|clew
clew|target/release/clew-install|clew-install'
PROVIDERS='clew|clew|clew/chancery|3'
