PIPELINE_SCHEMA=1
PRODUCT_ID=clew
PRODUCT_NAME=Clew
PRODUCT_DIR=products/clew
STATUS_SCHEMA=1
STATUS_COMMAND=clew
STATUS_UNITS='clew/ledger|on_demand||clew.ledger.use
clew/daily-email|active|clew/daily-email|clew.digest.email'
RELEASE_BRANCH=main
CARGO_MANIFEST=Cargo.toml
CARGO_PACKAGES=clew
CARGO_OFFLINE=1
CI_SHELL_CHECKS='sh|products/clew/release.sh'
RELEASE_UNITS='clew|Clew|package|products/clew/Cargo.toml|clew-|1'
RELEASE_BINARY_CHECKS='clew|target/release/clew|clew
clew|target/release/clew-install|clew-install'
PROVIDERS='clew|clew|products/clew/chancery|5'
