PIPELINE_SCHEMA=1
PRODUCT_ID=clockwork
PRODUCT_NAME=Clockwork
PRODUCT_DIR=infrastructure/clockwork
STATUS_SCHEMA=1
STATUS_COMMAND=clockwork
STATUS_UNITS='clockwork/schedules|active||clockwork.schedule.operate'
RELEASE_BRANCH=main
CARGO_MANIFEST=Cargo.toml
CARGO_PACKAGES=clockwork
CARGO_OFFLINE=0
CLIPPY_KEEP_GOING=1
CI_SHELL_CHECKS='sh|infrastructure/clockwork/release.sh'
RELEASE_UNITS='clockwork|Clockwork|package|infrastructure/clockwork/crates/clockwork/Cargo.toml|clockwork-|1'
RELEASE_METADATA_NO_DEPS=1
RELEASE_BINARY_CHECKS='clockwork|target/release/clockwork|clockwork
clockwork|target/release/clockwork-install|clockwork-install'
PROVIDERS='clockwork|clockwork|infrastructure/clockwork/chancery|9'
