PIPELINE_SCHEMA=1
PRODUCT_ID=clockwork
PRODUCT_NAME=Clockwork
PRODUCT_DIR=clockwork
CI_RESOURCE_CLASS=heavy
RELEASE_BRANCH=main
DEPLOY_PROFILE=custom
DEPLOY_CONFLICT_KEYS='global'
CARGO_MANIFEST=Cargo.toml
CARGO_PACKAGES=clockwork
CARGO_OFFLINE=0
CLIPPY_KEEP_GOING=1
TEST_NO_FAIL_FAST=1
CI_SHELL_CHECKS='sh|clockwork/release.sh
sh|clockwork/packaging/macos/deploy-user.sh
sh|clockwork/packaging/macos/uninstall-user.sh
sh|clockwork/packaging/macos/test-deploy-user.sh'
CI_RUN_CHECKS='darwin|clockwork/packaging/macos/test-deploy-user.sh'
CI_PROVIDER_VALIDATION_PHASE=before-rust
RELEASE_UNITS='clockwork|Clockwork|package|clockwork/crates/clockwork/Cargo.toml|clockwork-|1'
RELEASE_METADATA_NO_DEPS=1
RELEASE_BINARY_CHECKS='clockwork|target/release/clockwork|clockwork'
PROVIDERS='clockwork|clockwork|clockwork/chancery|3'
