PIPELINE_SCHEMA=1
PRODUCT_ID=conatus
PRODUCT_NAME=Conatus
PRODUCT_DIR=conatus
STATUS_SCHEMA=1
STATUS_COMMAND=conatus
STATUS_UNITS='conatus/update|active|conatus/update|conatus.update.operate'
CI_RESOURCE_CLASS=heavy
RELEASE_BRANCH=main
DEPLOY_PROFILE=rust-install-v1
DEPLOY_CONFLICT_KEYS='product:conatus
chancery-catalog'
CARGO_MANIFEST=Cargo.toml
CARGO_PACKAGES=conatus
CARGO_OFFLINE=0
CI_SHELL_CHECKS='sh|conatus/release.sh'
CI_RUN_CHECKS=''
CI_PROVIDER_VALIDATION_PHASE=before-rust
RELEASE_UNITS='conatus|Conatus|package|conatus/Cargo.toml|conatus-|1'
RELEASE_METADATA_NO_DEPS=1
RELEASE_BINARY_CHECKS='conatus|target/release/conatus|conatus
conatus|target/release/conatus-install|conatus-install'
PROVIDERS='conatus|conatus|conatus/chancery|3'
