PIPELINE_SCHEMA=1
PRODUCT_ID=conversations
PRODUCT_NAME=Conversations
PRODUCT_DIR=conversations
CI_RESOURCE_CLASS=heavy
RELEASE_BRANCH=main
DEPLOY_PROFILE=rust-install-v1
DEPLOY_CONFLICT_KEYS='product:conversations
chancery-catalog'
CARGO_MANIFEST=Cargo.toml
CARGO_PACKAGES=conversations
CARGO_OFFLINE=0
CLIPPY_KEEP_GOING=1
TEST_NO_FAIL_FAST=1
CI_SHELL_CHECKS='sh|conversations/release.sh'
CI_RUN_CHECKS=''
CI_PROVIDER_VALIDATION_PHASE=before-rust
RELEASE_UNITS='conversations|Conversations|package|conversations/crates/conversations/Cargo.toml|conversations-|1'
RELEASE_METADATA_NO_DEPS=1
RELEASE_BINARY_CHECKS='conversations|target/release/conversations|conversations
conversations|target/release/conversations-install|conversations-install'
PROVIDERS='conversations|conversations|conversations/chancery|2'
