PIPELINE_SCHEMA=1
PRODUCT_ID=conversations
PRODUCT_NAME=Conversations
PRODUCT_DIR=products/conversations
STATUS_SCHEMA=1
STATUS_COMMAND=conversations
STATUS_UNITS='conversations/history|on_demand||conversations.history.explore'
RELEASE_BRANCH=main
CARGO_MANIFEST=Cargo.toml
CARGO_PACKAGES=conversations
CARGO_OFFLINE=0
CLIPPY_KEEP_GOING=1
CI_SHELL_CHECKS='sh|products/conversations/release.sh'
RELEASE_UNITS='conversations|Conversations|package|products/conversations/crates/conversations/Cargo.toml|conversations-|1'
RELEASE_METADATA_NO_DEPS=1
RELEASE_BINARY_CHECKS='conversations|target/release/conversations|conversations
conversations|target/release/conversations-install|conversations-install'
PROVIDERS='conversations|conversations|products/conversations/chancery|4'
