PIPELINE_SCHEMA=1
PRODUCT_ID=crm
PRODUCT_NAME=CRM
PRODUCT_DIR=crm
CI_RESOURCE_CLASS=heavy
RELEASE_BRANCH=main
DEPLOY_PROFILE=rust-install-v1
DEPLOY_CONFLICT_KEYS='product:crm
chancery-catalog'
CARGO_MANIFEST=Cargo.toml
CARGO_PACKAGES=crm
CARGO_OFFLINE=0
CLIPPY_KEEP_GOING=1
TEST_NO_FAIL_FAST=1
CI_SHELL_CHECKS='sh|crm/release.sh'
CI_RUN_CHECKS=''
CI_PROVIDER_VALIDATION_PHASE=before-rust
RELEASE_UNITS='crm|CRM|package|crm/crates/crm/Cargo.toml|crm-|1'
RELEASE_METADATA_NO_DEPS=1
RELEASE_BINARY_CHECKS='crm|target/release/crm|crm
crm|target/release/crm-install|crm-install'
PROVIDERS='crm|crm|crm/chancery|5'
