PIPELINE_SCHEMA=1
PRODUCT_ID=decisions
PRODUCT_NAME=Krisis
PRODUCT_DIR=products/decisions
STATUS_SCHEMA=1
STATUS_COMMAND=krisis
STATUS_UNITS='krisis/observer|active|krisis/observer|krisis.install.operate
decisions/observer|retired|decisions/observer|decisions.lifecycle.consume
decisions/daily-email|retired|decisions/daily-email|decisions.lifecycle.consume'
RELEASE_BRANCH=main
PRODUCT_ALIASES='krisis decisions'
CARGO_MANIFEST=Cargo.toml
CARGO_PACKAGES='decisions
krisis-api'
CARGO_OFFLINE=0
CARGO_PATH_PREFIX=/Users/joey/.cargo/bin
CLIPPY_KEEP_GOING=0
CI_SHELL_CHECKS='sh|products/decisions/release.sh
sh|products/decisions/packaging/macos/krisis
sh|products/decisions/packaging/macos/krisis-observer'
CI_PLIST_CHECKS='always|convert|products/decisions/packaging/macos/hooks.json'
RELEASE_UNITS='krisis|Krisis|package|products/decisions/crates/decisions/Cargo.toml|krisis-|1'
RELEASE_COMPANION_MANIFESTS='krisis|products/decisions/crates/krisis-api/Cargo.toml'
RELEASE_METADATA_NO_DEPS=1
RELEASE_BINARY_CHECKS='krisis|target/release/krisis|krisis
krisis|target/release/krisis-install|krisis-install'
PROVIDERS='krisis|krisis|products/decisions/chancery|3
krisis|decisions|products/decisions/chancery-legacy|1'
