PIPELINE_SCHEMA=1
PRODUCT_ID=email
PRODUCT_NAME=Email
PRODUCT_DIR=email
CI_RESOURCE_CLASS=heavy
RELEASE_BRANCH=main
DEPLOY_PROFILE=custom
DEPLOY_CONFLICT_KEYS='global'
CARGO_MANIFEST=Cargo.toml
CARGO_PACKAGES=email
CARGO_OFFLINE=0
CLIPPY_KEEP_GOING=1
TEST_NO_FAIL_FAST=1
CI_SHELL_CHECKS='sh|email/release.sh
sh|email/packaging/macos/deploy-user.sh
sh|email/packaging/macos/test-deploy-user.sh
zsh|email/packaging/macos/email'
CI_RUN_CHECKS='darwin|email/packaging/macos/test-deploy-user.sh'
CI_PROVIDER_VALIDATION_PHASE=before-rust
RELEASE_UNITS='email|Email|package|email/crates/email/Cargo.toml|email-|1'
RELEASE_METADATA_NO_DEPS=1
RELEASE_BINARY_CHECKS='email|target/release/email|email'
PROVIDERS='email|email|email/chancery|1'
