PIPELINE_SCHEMA=1
PRODUCT_ID=emt
PRODUCT_NAME=EMT
PRODUCT_DIR=infrastructure/emt
STATUS_SCHEMA=1
STATUS_COMMAND=emt
STATUS_UNITS='emt/worker|active|emt/worker|emt.installation.operate'
RELEASE_BRANCH=main
CARGO_MANIFEST=Cargo.toml
CARGO_PACKAGES=emt
CARGO_OFFLINE=0
CLIPPY_KEEP_GOING=1
CI_SHELL_CHECKS='sh|infrastructure/emt/release.sh'
RELEASE_UNITS='emt|EMT|package|infrastructure/emt/Cargo.toml|emt-|1'
RELEASE_METADATA_NO_DEPS=1
RELEASE_BINARY_CHECKS='emt|target/release/emt|emt
emt|target/release/emt-install|emt-install'
PROVIDERS='emt|emt|infrastructure/emt/chancery|5'
