PIPELINE_SCHEMA=1
PRODUCT_ID=emt
PRODUCT_NAME=EMT
PRODUCT_DIR=emt
STATUS_SCHEMA=1
STATUS_COMMAND=emt
STATUS_UNITS='emt/worker|active|emt/worker|emt.installation.operate'
CI_RESOURCE_CLASS=heavy
RELEASE_BRANCH=main
DEPLOY_PROFILE=rust-install-v1
DEPLOY_CONFLICT_KEYS='product:emt
chancery-catalog'
CARGO_MANIFEST=Cargo.toml
CARGO_PACKAGES=emt
CARGO_OFFLINE=0
CLIPPY_KEEP_GOING=1
TEST_NO_FAIL_FAST=1
CI_SHELL_CHECKS='sh|emt/release.sh'
CI_RUN_CHECKS=''
CI_PROVIDER_VALIDATION_PHASE=before-rust
RELEASE_UNITS='emt|EMT|package|emt/Cargo.toml|emt-|1'
RELEASE_METADATA_NO_DEPS=1
RELEASE_BINARY_CHECKS='emt|target/release/emt|emt
emt|target/release/emt-install|emt-install'
PROVIDERS='emt|emt|emt/chancery|3'
