PIPELINE_SCHEMA=1
PRODUCT_ID=geste
PRODUCT_NAME=Geste
PRODUCT_DIR=geste
CI_RESOURCE_CLASS=heavy
RELEASE_BRANCH=main
DEPLOY_PROFILE=rust-install-v1
DEPLOY_CONFLICT_KEYS='product:geste
chancery-catalog'
CARGO_MANIFEST=Cargo.toml
CARGO_PACKAGES=geste
CARGO_OFFLINE=0
CLIPPY_KEEP_GOING=1
TEST_NO_FAIL_FAST=1
CI_SHELL_CHECKS='sh|geste/release.sh'
CI_RUN_CHECKS=''
CI_PROVIDER_VALIDATION_PHASE=before-rust
RELEASE_UNITS='geste|Geste|package|geste/crates/geste/Cargo.toml|geste-|1'
RELEASE_METADATA_NO_DEPS=1
RELEASE_BINARY_CHECKS='geste|target/release/geste|geste
geste|target/release/geste-install|geste-install'
PROVIDERS='geste|geste|geste/chancery|4'
