PIPELINE_SCHEMA=1
PRODUCT_ID=iatreion
PRODUCT_NAME=Iatreion
PRODUCT_DIR=iatreion
STATUS_SCHEMA=1
STATUS_COMMAND=iatreion
STATUS_UNITS='iatreion/report|on_demand||iatreion.status.inspect'
CI_RESOURCE_CLASS=heavy
RELEASE_BRANCH=main
DEPLOY_PROFILE=rust-install-v1
DEPLOY_CONFLICT_KEYS='product:iatreion
chancery-catalog'
CARGO_MANIFEST=Cargo.toml
CARGO_PACKAGES='iatreion
iatreion-api'
CARGO_OFFLINE=0
CLIPPY_KEEP_GOING=1
TEST_NO_FAIL_FAST=1
CI_SHELL_CHECKS='sh|iatreion/release.sh'
CI_RUN_CHECKS=''
CI_PROVIDER_VALIDATION_PHASE=before-rust
RELEASE_UNITS='iatreion|Iatreion|package|iatreion/crates/iatreion/Cargo.toml|iatreion-|1'
RELEASE_COMPANION_MANIFESTS='iatreion|iatreion/crates/iatreion-api/Cargo.toml'
RELEASE_METADATA_NO_DEPS=1
RELEASE_BINARY_CHECKS='iatreion|target/release/iatreion|iatreion
iatreion|target/release/iatreion-install|iatreion-install'
CI_BINARY_CHECKS='iatreion|target/release/iatreion|iatreion
iatreion|target/release/iatreion-install|iatreion-install'
PROVIDERS='iatreion|iatreion|iatreion/chancery|3'
