PIPELINE_SCHEMA=1
PRODUCT_ID=job-packets
PRODUCT_NAME='Job Packets'
PRODUCT_DIR=job-packets
CI_RESOURCE_CLASS=heavy
RELEASE_BRANCH=main
DEPLOY_PROFILE=custom
DEPLOY_CONFLICT_KEYS='global'
CARGO_MANIFEST=Cargo.toml
CARGO_PACKAGES=job-packets
CARGO_OFFLINE=0
CLIPPY_KEEP_GOING=1
TEST_NO_FAIL_FAST=1
CI_SHELL_CHECKS='sh|job-packets/release.sh'
CI_RUN_CHECKS=''
CI_PROVIDER_VALIDATION_PHASE=before-rust
RELEASE_UNITS='job-packets|Job Packets|package|job-packets/Cargo.toml|job-packets-|1'
RELEASE_METADATA_NO_DEPS=1
RELEASE_BINARY_CHECKS='job-packets|target/release/job-packets|job-packets'
PROVIDERS='job-packets|job-packets|job-packets/chancery|1'
