PIPELINE_SCHEMA=1
PRODUCT_ID=mentor
PRODUCT_NAME=Mentor
PRODUCT_DIR=mentor
STATUS_SCHEMA=1
STATUS_COMMAND=mentor
STATUS_UNITS='mentor/worker|active|mentor/worker|mentor.installation.operate'
CI_RESOURCE_CLASS=heavy
RELEASE_BRANCH=main
DEPLOY_PROFILE=rust-install-v1
DEPLOY_CONFLICT_KEYS='product:mentor
chancery-catalog'
CARGO_MANIFEST=Cargo.toml
CARGO_PACKAGES=mentor
CARGO_OFFLINE=0
CLIPPY_KEEP_GOING=1
TEST_NO_FAIL_FAST=1
CI_SHELL_CHECKS='sh|mentor/release.sh'
CI_RUN_CHECKS=''
CI_PROVIDER_VALIDATION_PHASE=before-rust
RELEASE_UNITS='mentor|Mentor|package|mentor/Cargo.toml|mentor-|1'
RELEASE_METADATA_NO_DEPS=1
RELEASE_BINARY_CHECKS='mentor|target/release/mentor|mentor
mentor|target/release/mentor-install|mentor-install'
PROVIDERS='mentor|mentor|mentor/chancery|3'
