PIPELINE_SCHEMA=1
PRODUCT_ID=milieu
PRODUCT_NAME=Milieu
PRODUCT_DIR=products/milieu
STATUS_SCHEMA=1
STATUS_COMMAND=milieu
STATUS_UNITS='milieu/discovery|on_demand||milieu.discovery.explore'
RELEASE_BRANCH=main
CARGO_MANIFEST=Cargo.toml
CARGO_PACKAGES=milieu
CARGO_OFFLINE=0
CLIPPY_KEEP_GOING=1
CI_SHELL_CHECKS='sh|products/milieu/release.sh'
RELEASE_UNITS='milieu|Milieu|package|products/milieu/Cargo.toml|milieu-|1'
RELEASE_METADATA_NO_DEPS=1
RELEASE_BINARY_CHECKS='milieu|target/release/milieu|milieu
milieu|target/release/milieu-install|milieu-install'
PROVIDERS='milieu|milieu|products/milieu/chancery|4'
