PIPELINE_SCHEMA=1
PRODUCT_ID=nucleus
PRODUCT_NAME=Nucleus
PRODUCT_DIR=nucleus
CI_RESOURCE_CLASS=heavy
RELEASE_BRANCH=main
DEPLOY_PROFILE=custom
DEPLOY_CONFLICT_KEYS='global'
CARGO_MANIFEST=Cargo.toml
CARGO_PACKAGES='nucleus-cli
nucleus-client
nucleus-core
nucleus-codex
nucleus-daemon
nucleus-store'
CARGO_OFFLINE=0
CLIPPY_KEEP_GOING=1
TEST_NO_FAIL_FAST=1
CI_SHELL_CHECKS='sh|nucleus/release.sh
sh|nucleus/packaging/macos/deploy-user.sh
sh|nucleus/packaging/macos/test-deploy-user.sh'
CI_RUN_CHECKS='always|nucleus/packaging/macos/test-deploy-user.sh'
CI_PROVIDER_VALIDATION_PHASE=before-rust
RELEASE_UNITS='nucleus|Nucleus|workspace-package|Cargo.toml|nucleus-|1'
RELEASE_METADATA_NO_DEPS=0
RELEASE_BINARY_CHECKS='nucleus|target/release/nucleus|nucleus
nucleus|target/release/nucleusd|nucleusd'
PROVIDERS='nucleus|nucleus|nucleus/chancery|3'
