PIPELINE_SCHEMA=1
PRODUCT_ID=nucleus
PRODUCT_NAME=Nucleus
PRODUCT_DIR=infrastructure/nucleus
STATUS_SCHEMA=1
STATUS_COMMAND=nucleus
STATUS_UNITS='nucleus/service|active||nucleus.execution.operate'
RELEASE_BRANCH=main
CARGO_MANIFEST=Cargo.toml
CARGO_PACKAGES='nucleus-cli
nucleus-client
nucleus-core
nucleus-codex
nucleus-daemon
nucleus-store'
CARGO_OFFLINE=0
CLIPPY_KEEP_GOING=1
CI_SHELL_CHECKS='sh|infrastructure/nucleus/release.sh'
RELEASE_UNITS='nucleus|Nucleus|workspace-package|Cargo.toml|nucleus-|1'
RELEASE_METADATA_NO_DEPS=0
RELEASE_BINARY_CHECKS='nucleus|target/release/nucleus|nucleus
nucleus|target/release/nucleusd|nucleusd
nucleus|target/release/nucleus-install|nucleus-install'
PROVIDERS='nucleus|nucleus|infrastructure/nucleus/chancery|10'
