PIPELINE_SCHEMA=1
PRODUCT_ID=paperboy
PRODUCT_NAME=Paperboy
PRODUCT_DIR=products/paperboy
STATUS_SCHEMA=1
STATUS_COMMAND=paperboy
STATUS_UNITS='paperboy/productions|on_demand||paperboy.install.operate'
RELEASE_BRANCH=main
CARGO_MANIFEST=Cargo.toml
CARGO_PACKAGES=paperboy
CARGO_OFFLINE=1
CLIPPY_KEEP_GOING=1
CI_SHELL_CHECKS='sh|products/paperboy/release.sh'
RELEASE_UNITS='paperboy|Paperboy|package|products/paperboy/Cargo.toml|paperboy-|1'
RELEASE_METADATA_NO_DEPS=1
RELEASE_BINARY_CHECKS='paperboy|target/release/paperboy|paperboy
paperboy|target/release/paperboy-install|paperboy-install'
PROVIDERS='paperboy|paperboy|products/paperboy/chancery|2'
