PIPELINE_SCHEMA=1
PRODUCT_ID=paperboy
PRODUCT_NAME=Paperboy
PRODUCT_DIR=paperboy
STATUS_SCHEMA=1
STATUS_COMMAND=paperboy
STATUS_UNITS='paperboy/daily|active|paperboy/daily|paperboy.install.operate'
CI_RESOURCE_CLASS=heavy
RELEASE_BRANCH=main
DEPLOY_PROFILE=rust-install-v1
DEPLOY_CONFLICT_KEYS='product:paperboy
chancery-catalog'
CARGO_MANIFEST=Cargo.toml
CARGO_PACKAGES=paperboy
CARGO_OFFLINE=1
CLIPPY_KEEP_GOING=1
TEST_NO_FAIL_FAST=1
CI_SHELL_CHECKS='sh|paperboy/release.sh'
CI_RUN_CHECKS=''
CI_PROVIDER_VALIDATION_PHASE=before-rust
RELEASE_UNITS='paperboy|Paperboy|package|paperboy/Cargo.toml|paperboy-|1'
RELEASE_METADATA_NO_DEPS=1
RELEASE_BINARY_CHECKS='paperboy|target/release/paperboy|paperboy
paperboy|target/release/paperboy-install|paperboy-install'
PROVIDERS='paperboy|paperboy|paperboy/chancery|2'
