PIPELINE_SCHEMA=1
PRODUCT_ID=platter
PRODUCT_NAME='Platter'
PRODUCT_DIR=platter
STATUS_SCHEMA=1
STATUS_COMMAND=platter
STATUS_UNITS='platter/daily|active|platter/daily|platter.install.operate'
CI_RESOURCE_CLASS=heavy
RELEASE_BRANCH=main
DEPLOY_PROFILE=rust-install-v1
DEPLOY_CONFLICT_KEYS='product:platter
chancery-catalog'
CARGO_MANIFEST=Cargo.toml
CARGO_PACKAGES=platter
CARGO_OFFLINE=0
CLIPPY_KEEP_GOING=1
TEST_NO_FAIL_FAST=1
CI_SHELL_CHECKS='sh|platter/release.sh'
CI_RUN_CHECKS=''
CI_PROVIDER_VALIDATION_PHASE=before-rust
RELEASE_UNITS='platter|Platter|package|platter/Cargo.toml|platter-|1'
RELEASE_METADATA_NO_DEPS=1
RELEASE_BINARY_CHECKS='platter|target/release/platter|platter
platter|target/release/platter-install|platter-install'
PROVIDERS='platter|platter|platter/chancery|2'
