PIPELINE_SCHEMA=1
PRODUCT_ID=platter
PRODUCT_NAME='Platter'
PRODUCT_DIR=products/platter
STATUS_SCHEMA=1
STATUS_COMMAND=platter
STATUS_UNITS='platter/daily|active|platter/daily|platter.install.operate'
RELEASE_BRANCH=main
CARGO_MANIFEST=Cargo.toml
CARGO_PACKAGES=platter
CARGO_OFFLINE=0
CLIPPY_KEEP_GOING=1
CI_SHELL_CHECKS='sh|products/platter/release.sh'
RELEASE_UNITS='platter|Platter|package|products/platter/Cargo.toml|platter-|1'
RELEASE_METADATA_NO_DEPS=1
RELEASE_BINARY_CHECKS='platter|target/release/platter|platter
platter|target/release/platter-install|platter-install'
PROVIDERS='platter|platter|products/platter/chancery|7'
