PIPELINE_SCHEMA=1
PRODUCT_ID=pratica
PRODUCT_NAME=Pratica
PRODUCT_DIR=pratica
CI_RESOURCE_CLASS=heavy
RELEASE_BRANCH=main
DEPLOY_PROFILE=selector-only-v1
DEPLOY_CONFLICT_KEYS='product:pratica
chancery-catalog'
CARGO_MANIFEST=Cargo.toml
CARGO_PACKAGES=pratica
CARGO_OFFLINE=0
CLIPPY_KEEP_GOING=1
TEST_NO_FAIL_FAST=1
CI_SHELL_CHECKS='sh|pratica/release.sh
sh|pratica/packaging/macos/deploy-user.sh
sh|pratica/packaging/macos/test-deploy-user.sh'
CI_RUN_CHECKS='darwin|pratica/packaging/macos/test-deploy-user.sh'
CI_PROVIDER_VALIDATION_PHASE=before-rust
CI_EXTRA_BEFORE_RUST=pipeline/extras/deployment-generated.sh
RELEASE_UNITS='pratica|Pratica|package|pratica/crates/pratica/Cargo.toml|pratica-|1'
RELEASE_METADATA_NO_DEPS=1
RELEASE_BINARY_CHECKS='pratica|target/release/pratica|pratica'
PROVIDERS='pratica|pratica|pratica/chancery|4'
