PIPELINE_SCHEMA=1
PRODUCT_ID=semantics
PRODUCT_NAME=Semantics
PRODUCT_DIR=infrastructure/semantics
STATUS_SCHEMA=1
STATUS_COMMAND=semantics
STATUS_UNITS='semantics/worker|active|semantics/worker|semantics.project.operate'
RELEASE_BRANCH=main
CARGO_MANIFEST=infrastructure/semantics/Cargo.toml
CARGO_PACKAGES=semantics
CARGO_OFFLINE=1
CARGO_PATH_PREFIX=/Users/joey/.cargo/bin
CLIPPY_KEEP_GOING=0
CI_SHELL_CHECKS='sh|infrastructure/semantics/release.sh
sh|infrastructure/semantics/packaging/macos/semantics
sh|infrastructure/semantics/packaging/macos/semantics-worker'
CI_PLIST_CHECKS='always|lint|infrastructure/semantics/packaging/macos/org.semantics.worker.plist'
RELEASE_UNITS='semantics|Semantics|package|infrastructure/semantics/Cargo.toml|semantics-|1'
RELEASE_METADATA_NO_DEPS=1
RELEASE_BINARY_CHECKS='semantics|target/release/semantics|semantics
semantics|target/release/semantics-install|semantics-install'
PROVIDERS='semantics|semantics|infrastructure/semantics/chancery|6'
