PIPELINE_SCHEMA=1
PRODUCT_ID=semantics
PRODUCT_NAME=Semantics
PRODUCT_DIR=semantics
CI_RESOURCE_CLASS=heavy
RELEASE_BRANCH=main
DEPLOY_PROFILE=custom
DEPLOY_CONFLICT_KEYS='global'
CARGO_MANIFEST=semantics/Cargo.toml
CARGO_PACKAGES=semantics
CARGO_OFFLINE=1
CARGO_PATH_PREFIX=/Users/joey/.cargo/bin
CLIPPY_KEEP_GOING=0
TEST_NO_FAIL_FAST=0
CI_SHELL_CHECKS='sh|semantics/release.sh
sh|semantics/packaging/macos/semantics
sh|semantics/packaging/macos/deploy-user.sh
sh|semantics/packaging/macos/uninstall-user.sh
sh|semantics/packaging/macos/test-frontend.sh
sh|semantics/packaging/macos/test-worker-runner.sh
sh|semantics/packaging/macos/test-deploy-user.sh
sh|semantics/packaging/macos/semantics-worker'
CI_RUN_CHECKS='always|semantics/packaging/macos/test-frontend.sh
always|semantics/packaging/macos/test-worker-runner.sh
always|semantics/packaging/macos/test-deploy-user.sh'
CI_PLIST_CHECKS='always|lint|semantics/packaging/macos/org.semantics.worker.plist'
CI_PROVIDER_VALIDATION_PHASE=before-rust
CI_EXTRA_BEFORE_RUST=pipeline/extras/semantics-catalog.sh
RELEASE_UNITS='semantics|Semantics|package|semantics/Cargo.toml|semantics-|1'
RELEASE_METADATA_NO_DEPS=1
RELEASE_BINARY_CHECKS='semantics|target/release/semantics|semantics'
PROVIDERS='semantics|semantics|semantics/chancery|3'
