PIPELINE_SCHEMA=1
PRODUCT_ID=todo
PRODUCT_NAME=Todo
PRODUCT_DIR=todo
CI_RESOURCE_CLASS=heavy
RELEASE_BRANCH=main
DEPLOY_PROFILE=custom
DEPLOY_CONFLICT_KEYS='global'
CARGO_MANIFEST=Cargo.toml
CARGO_PACKAGES=todo
CARGO_OFFLINE=0
CLIPPY_KEEP_GOING=1
TEST_NO_FAIL_FAST=1
CI_SHELL_CHECKS='sh|todo/release.sh
sh|todo/packaging/macos/todo
sh|todo/packaging/macos/deploy-user.sh
sh|todo/packaging/macos/test-frontend.sh
sh|todo/packaging/macos/test-deploy-user.sh'
CI_RUN_CHECKS='always|todo/packaging/macos/test-frontend.sh
always|todo/packaging/macos/test-deploy-user.sh'
CI_PROVIDER_VALIDATION_PHASE=before-rust
CI_EXTRA_BEFORE_RUST=pipeline/extras/todo-catalog.sh
RELEASE_UNITS='todo|Todo|package|todo/crates/todo/Cargo.toml|todo-|1'
RELEASE_METADATA_NO_DEPS=0
RELEASE_BINARY_CHECKS='todo|target/release/todo|todo'
PROVIDERS='todo|todo|todo/chancery|7'
