PIPELINE_SCHEMA=1
PRODUCT_ID=usher
PRODUCT_NAME=Usher
PRODUCT_DIR=usher
CI_RESOURCE_CLASS=heavy
RELEASE_BRANCH=main
DEPLOY_PROFILE=rust-install-v1
DEPLOY_CONFLICT_KEYS='product:usher
chancery-catalog'
CARGO_MANIFEST=Cargo.toml
CARGO_PACKAGES='cell-install
usher'
CARGO_OFFLINE=1
CI_SHELL_CHECKS='sh|usher/release.sh'
CI_RUN_CHECKS=''
CI_PROVIDER_VALIDATION_PHASE=before-rust
RELEASE_UNITS='usher|Usher|package|usher/crates/usher/Cargo.toml|usher-|1'
RELEASE_BINARY_CHECKS='usher|target/release/usher|usher
usher|target/release/usher-install|usher-install'
CI_BINARY_CHECKS='usher|target/release/usher|usher
usher|target/release/usher-install|usher-install'
PROVIDERS='usher|usher|usher/chancery|3'
