PIPELINE_SCHEMA=1
PRODUCT_ID=usher
PRODUCT_NAME=Usher
PRODUCT_DIR=usher
CI_RESOURCE_CLASS=heavy
RELEASE_BRANCH=main
DEPLOY_PROFILE=selector-only-v1
DEPLOY_CONFLICT_KEYS='product:usher
chancery-catalog'
CARGO_MANIFEST=Cargo.toml
CARGO_PACKAGES=usher
CARGO_OFFLINE=1
CI_SHELL_CHECKS='sh|usher/release.sh
sh|usher/packaging/macos/deploy-user.sh
sh|usher/packaging/macos/test-deploy-user.sh'
CI_RUN_CHECKS='darwin|usher/packaging/macos/test-deploy-user.sh'
CI_PROVIDER_VALIDATION_PHASE=before-rust
CI_EXTRA_BEFORE_RUST=pipeline/extras/deployment-generated.sh
RELEASE_UNITS='usher|Usher|package|usher/crates/usher/Cargo.toml|usher-|1'
RELEASE_BINARY_CHECKS='usher|target/release/usher|usher'
CI_BINARY_CHECKS='usher|target/release/usher|usher'
PROVIDERS='usher|usher|usher/chancery|3'
