PIPELINE_SCHEMA=1
PRODUCT_ID=vizier
PRODUCT_NAME=Vizier
PRODUCT_DIR=vizier
CI_RESOURCE_CLASS=heavy
RELEASE_BRANCH=main
DEPLOY_PROFILE=selector-only-v1
DEPLOY_CONFLICT_KEYS='product:vizier
chancery-catalog'
CARGO_MANIFEST=Cargo.toml
CARGO_PACKAGES=vizier
CARGO_OFFLINE=0
CLIPPY_KEEP_GOING=1
TEST_NO_FAIL_FAST=1
CI_SHELL_CHECKS='sh|vizier/release.sh
sh|vizier/packaging/macos/deploy-user.sh
sh|vizier/packaging/macos/test-deploy-user.sh'
CI_RUN_CHECKS='darwin|vizier/packaging/macos/test-deploy-user.sh'
CI_PROVIDER_VALIDATION_PHASE=before-rust
CI_EXTRA_BEFORE_RUST=pipeline/extras/deployment-generated.sh
RELEASE_UNITS='vizier|Vizier|package|vizier/crates/vizier/Cargo.toml|vizier-|1'
RELEASE_METADATA_NO_DEPS=1
RELEASE_BINARY_CHECKS='vizier|target/release/vizier|vizier'
PROVIDERS='vizier|vizier|vizier/chancery|3'
