PIPELINE_SCHEMA=1
PRODUCT_ID=weaver
PRODUCT_NAME=Weaver
PRODUCT_DIR=weaver-narrative
STATUS_SCHEMA=1
STATUS_COMMAND=weaver
STATUS_UNITS='weaver/author|on_demand||weaver.install.operate'
CI_RESOURCE_CLASS=heavy
RELEASE_BRANCH=main
DEPLOY_PROFILE=rust-install-v1
DEPLOY_CONFLICT_KEYS='product:weaver
chancery-catalog'
CARGO_MANIFEST=Cargo.toml
CARGO_PACKAGES=weaver
CARGO_OFFLINE=1
CLIPPY_KEEP_GOING=1
TEST_NO_FAIL_FAST=1
CI_SHELL_CHECKS='sh|weaver-narrative/release.sh'
CI_RUN_CHECKS=''
CI_PROVIDER_VALIDATION_PHASE=before-rust
RELEASE_UNITS='weaver|Weaver|package|weaver-narrative/Cargo.toml|weaver-|1'
RELEASE_METADATA_NO_DEPS=1
RELEASE_BINARY_CHECKS='weaver|target/release/weaver|weaver
weaver|target/release/weaver-install|weaver-install'
PROVIDERS='weaver|weaver|weaver-narrative/chancery|3'
