#!/bin/sh
# Generated by deployment/generate.py from deployment/products.json.
# Do not edit this file directly.

set -eu

PATH=/usr/bin:/bin:/usr/sbin:/sbin
export PATH
umask 077

PRODUCT_ID=usher
DISPLAY_NAME=Usher
APPLICATION_SUPPORT_NAME=Usher
BINARY_NAME=usher
PROVIDER_ID=usher
MANIFEST_PRODUCT_LINE=1
PRINT_STATE_PATH=0
COMPLETION_NOTE='Recognition reads repository declarations only.'

SCRIPT_DIR=$(CDPATH='' cd "$(dirname "$0")" && pwd)
SOURCE_DEPLOYER="$SCRIPT_DIR/deploy-user.sh"
if [ -d "$SCRIPT_DIR/../share/chancery/$PROVIDER_ID" ]; then
    SOURCE_CHANCERY="$SCRIPT_DIR/../share/chancery/$PROVIDER_ID"
else
    SOURCE_CHANCERY="$SCRIPT_DIR/../../chancery"
fi

binary_path=
install_home=${HOME:-}
expected_current=
expected_current_set=0
lock_wait_seconds=${CELL_DEPLOY_LOCK_WAIT_SECONDS:-300}

usage() {
    cat <<EOF
Usage: deploy-user.sh --binary ABSOLUTE_PATH [OPTIONS]

Install or update the current user's stateless Usher CLI and product-owned
Chancery provider. No semantic registration or service state is changed.

Options:
  --home ABSOLUTE_PATH       Override the operator home (primarily for tests)
  --expected-current VALUE  Require absent or releases/<sha256> before cutover
EOF
}

fail() {
    printf '%s user deploy: %s\n' "$PRODUCT_ID" "$*" >&2
    exit 1
}

while [ "$#" -gt 0 ]; do
    case "$1" in
        --binary)
            [ "$#" -ge 2 ] || fail '--binary requires a path'
            binary_path=$2
            shift 2
            ;;
        --home)
            [ "$#" -ge 2 ] || fail '--home requires a path'
            install_home=$2
            shift 2
            ;;
        --expected-current)
            [ "$#" -ge 2 ] || fail '--expected-current requires a value'
            [ "$expected_current_set" -eq 0 ] \
                || fail '--expected-current may be supplied only once'
            expected_current=$2
            expected_current_set=1
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *) fail "unknown argument: $1" ;;
    esac
done

[ -n "$binary_path" ] || fail '--binary is required'
[ -n "$install_home" ] || fail '--home is required'
case "$binary_path" in /*) ;; *) fail 'binary path must be absolute' ;; esac
case "$install_home" in /*) ;; *) fail 'home path must be absolute' ;; esac
case "$lock_wait_seconds" in
    ''|*[!0-9]*) fail 'CELL_DEPLOY_LOCK_WAIT_SECONDS must be a nonnegative integer' ;;
esac
if [ "$expected_current_set" -eq 1 ]; then
    case "$expected_current" in
        absent) ;;
        releases/*)
            printf '%s\n' "$expected_current" \
                | grep -Eq '^releases/[0-9a-f]{64}$' \
                || fail '--expected-current must be absent or releases/<sha256>'
            ;;
        *) fail '--expected-current must be absent or releases/<sha256>' ;;
    esac
fi

[ -d "$install_home" ] && [ ! -L "$install_home" ] \
    || fail "operator home is not a regular directory: $install_home"
[ -f "$binary_path" ] && [ ! -L "$binary_path" ] && [ -x "$binary_path" ] \
    || fail "candidate is not an executable regular file: $binary_path"
[ -f "$SOURCE_DEPLOYER" ] && [ ! -L "$SOURCE_DEPLOYER" ] \
    || fail "packaged deployer is not a regular file: $SOURCE_DEPLOYER"
for command in awk cat chmod cp find grep id install ln mktemp mv readlink \
    rm sed sh shasum sleep sort stat
do
    command -v "$command" >/dev/null 2>&1 \
        || fail "required command not found: $command"
done
[ -x /usr/bin/shlock ] || fail 'required command not found: /usr/bin/shlock'

operator_uid=$(id -u)
[ "$operator_uid" -ne 0 ] || fail "run as the $DISPLAY_NAME operator, not root"
if operator_home_uid=$(stat -f '%u' "$install_home" 2>/dev/null); then
    :
elif operator_home_uid=$(stat -c '%u' "$install_home" 2>/dev/null); then
    :
else
    fail "unable to inspect home ownership: $install_home"
fi
[ "$operator_home_uid" = "$operator_uid" ] \
    || fail "operator home is not owned by uid $operator_uid: $install_home"

validate_bundle() {
    bundle=$1
    [ -d "$bundle" ] && [ ! -L "$bundle" ] \
        || fail "Chancery bundle is not a regular directory: $bundle"
    for directory in "$bundle/entries" "$bundle/manuals"; do
        [ -d "$directory" ] && [ ! -L "$directory" ] \
            || fail "Chancery bundle has an invalid directory: $directory"
    done
    [ -f "$bundle/provider.json" ] && [ ! -L "$bundle/provider.json" ] \
        || fail "Chancery bundle has no regular provider.json: $bundle"
    if find "$bundle" -type l -print | grep -q .; then
        fail "Chancery bundle contains a symbolic link: $bundle"
    fi
    if find "$bundle" ! -type d ! -type f -print | grep -q .; then
        fail "Chancery bundle contains a non-file entry: $bundle"
    fi
    actual_directories=$(
        cd "$bundle"
        find . -type d -print | LC_ALL=C sort
    )
    expected_directories=$(printf '%s\n' . ./entries ./manuals | LC_ALL=C sort)
    [ "$actual_directories" = "$expected_directories" ] \
        || fail "Chancery bundle has unexpected directories: $bundle"
    find "$bundle" -type f -print | while IFS= read -r file; do
        relative=${file#"$bundle"/}
        case "$relative" in
            provider.json|entries/*.json|manuals/*.md) ;;
            *) exit 1 ;;
        esac
    done || fail "Chancery bundle has an unexpected file: $bundle"
    find "$bundle/entries" -type f -name '*.json' -print | grep -q . \
        || fail "Chancery bundle has no entries: $bundle"
    find "$bundle/manuals" -type f -name '*.md' -print | grep -q . \
        || fail "Chancery bundle has no manuals: $bundle"
    bundle_provider=$(awk -F '"' \
        '/"id"[[:space:]]*:/ { print $4; exit }' "$bundle/provider.json")
    [ "$bundle_provider" = "$PROVIDER_ID" ] \
        || fail "Chancery bundle has an unexpected provider id: $bundle_provider"
}

bundle_hash() {
    bundle=$1
    (
        cd "$bundle"
        find . -type f -print | LC_ALL=C sort | while IFS= read -r file; do
            printf 'path=%s\n' "$file"
            shasum -a 256 "$file"
        done
    ) | shasum -a 256 | awk '{print $1}'
}

validate_release_selector() {
    selector=$1
    printf '%s\n' "$selector" | grep -Eq '^releases/[0-9a-f]{64}$' \
        || fail "invalid $DISPLAY_NAME release selector: $selector"
}

write_manifest() {
    manifest_release_id=$1
    manifest_version=$2
    manifest_binary_hash=$3
    manifest_deployer_hash=$4
    manifest_chancery_hash=$5
    printf '%s\n' 'format=1'
    if [ "$MANIFEST_PRODUCT_LINE" -eq 1 ]; then
        printf 'product=%s\n' "$PRODUCT_ID"
    fi
    printf 'release_id=%s\n' "$manifest_release_id"
    printf 'version=%s\n' "$manifest_version"
    printf 'binary_sha256=%s\n' "$manifest_binary_hash"
    printf 'deployer_sha256=%s\n' "$manifest_deployer_hash"
    printf 'chancery_sha256=%s\n' "$manifest_chancery_hash"
}

validate_installed_release() {
    selector=$1
    validate_release_selector "$selector"
    inspected_id=${selector#releases/}
    inspected_path="$INSTALL_DIR/$selector"

    for directory in "$inspected_path" "$inspected_path/bin" \
        "$inspected_path/package" "$inspected_path/share" \
        "$inspected_path/share/chancery" \
        "$inspected_path/share/chancery/$PROVIDER_ID"; do
        [ -d "$directory" ] && [ ! -L "$directory" ] \
            || fail "installed release has an invalid directory: $selector"
    done
    if find "$inspected_path" -type l -print | grep -q .; then
        fail "installed release contains a symbolic link: $selector"
    fi
    if find "$inspected_path" ! -type d ! -type f -print | grep -q .; then
        fail "installed release contains a non-file entry: $selector"
    fi
    actual_release_directories=$(
        cd "$inspected_path"
        find . -type d -print | LC_ALL=C sort
    )
    expected_release_directories=$(printf '%s\n' \
        . ./bin ./package ./share ./share/chancery \
        "./share/chancery/$PROVIDER_ID" \
        "./share/chancery/$PROVIDER_ID/entries" \
        "./share/chancery/$PROVIDER_ID/manuals" | LC_ALL=C sort)
    [ "$actual_release_directories" = "$expected_release_directories" ] \
        || fail "installed release tree is not the exact selector-only layout: $selector"
    find "$inspected_path" -type f -print | while IFS= read -r file; do
        relative=${file#"$inspected_path"/}
        case "$relative" in
            "bin/$BINARY_NAME"|package/deploy-user.sh|manifest.txt|\
            "share/chancery/$PROVIDER_ID/provider.json"|\
            "share/chancery/$PROVIDER_ID/entries/"*.json|\
            "share/chancery/$PROVIDER_ID/manuals/"*.md) ;;
            *) exit 1 ;;
        esac
    done || fail "installed release tree has an unexpected file: $selector"
    [ -f "$inspected_path/bin/$BINARY_NAME" ] \
        && [ ! -L "$inspected_path/bin/$BINARY_NAME" ] \
        && [ -x "$inspected_path/bin/$BINARY_NAME" ] \
        || fail "installed release has an invalid binary: $selector"
    [ -f "$inspected_path/package/deploy-user.sh" ] \
        && [ ! -L "$inspected_path/package/deploy-user.sh" ] \
        && [ -x "$inspected_path/package/deploy-user.sh" ] \
        || fail "installed release has an invalid deployer: $selector"
    [ -f "$inspected_path/manifest.txt" ] \
        && [ ! -L "$inspected_path/manifest.txt" ] \
        || fail "installed release has an invalid manifest: $selector"
    validate_bundle "$inspected_path/share/chancery/$PROVIDER_ID"

    manifest="$inspected_path/manifest.txt"
    if [ "$MANIFEST_PRODUCT_LINE" -eq 1 ]; then
        [ "$(awk 'END { print NR }' "$manifest")" -eq 7 ] \
            || fail "installed release manifest is not canonical: $selector"
        [ "$(sed -n '1p' "$manifest")" = 'format=1' ] \
            && [ "$(sed -n '2p' "$manifest")" = "product=$PRODUCT_ID" ] \
            || fail "installed release manifest has foreign ownership: $selector"
        inspected_manifest_id=$(sed -n '3s/^release_id=//p' "$manifest")
        inspected_version=$(sed -n '4s/^version=//p' "$manifest")
        inspected_binary_hash=$(sed -n '5s/^binary_sha256=//p' "$manifest")
        inspected_deployer_hash=$(sed -n '6s/^deployer_sha256=//p' "$manifest")
        inspected_chancery_hash=$(sed -n '7s/^chancery_sha256=//p' "$manifest")
    else
        [ "$(awk 'END { print NR }' "$manifest")" -eq 6 ] \
            || fail "installed release manifest is not canonical: $selector"
        [ "$(sed -n '1p' "$manifest")" = 'format=1' ] \
            || fail "installed release manifest format is unsupported: $selector"
        inspected_manifest_id=$(sed -n '2s/^release_id=//p' "$manifest")
        inspected_version=$(sed -n '3s/^version=//p' "$manifest")
        inspected_binary_hash=$(sed -n '4s/^binary_sha256=//p' "$manifest")
        inspected_deployer_hash=$(sed -n '5s/^deployer_sha256=//p' "$manifest")
        inspected_chancery_hash=$(sed -n '6s/^chancery_sha256=//p' "$manifest")
    fi
    [ "$inspected_manifest_id" = "$inspected_id" ] \
        || fail "installed release manifest identity is invalid: $selector"
    printf '%s\n' "$inspected_manifest_id" "$inspected_binary_hash" \
        "$inspected_deployer_hash" "$inspected_chancery_hash" \
        | grep -Eqv '^[0-9a-f]{64}$' \
        && fail "installed release manifest hashes are invalid: $selector"
    printf '%s\n' "$inspected_version" \
        | grep -Eq '^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$' \
        || fail "installed release version is invalid: $selector"

    computed_binary_hash=$(shasum -a 256 \
        "$inspected_path/bin/$BINARY_NAME" | awk '{print $1}')
    computed_deployer_hash=$(shasum -a 256 \
        "$inspected_path/package/deploy-user.sh" | awk '{print $1}')
    computed_chancery_hash=$(bundle_hash \
        "$inspected_path/share/chancery/$PROVIDER_ID")
    [ "$computed_binary_hash" = "$inspected_binary_hash" ] \
        || fail "installed release binary is tampered: $selector"
    [ "$computed_deployer_hash" = "$inspected_deployer_hash" ] \
        || fail "installed release deployer is tampered: $selector"
    [ "$computed_chancery_hash" = "$inspected_chancery_hash" ] \
        || fail "installed release provider is tampered: $selector"
    computed_id=$(printf '%s\n' "$computed_binary_hash" \
        "$computed_deployer_hash" "$computed_chancery_hash" \
        | shasum -a 256 | awk '{print $1}')
    [ "$computed_id" = "$inspected_id" ] \
        || fail "installed release content identity is invalid: $selector"
    inspected_provider_version=$(awk -F '"' \
        '/"release"[[:space:]]*:/ { print $4; exit }' \
        "$inspected_path/share/chancery/$PROVIDER_ID/provider.json")
    [ "$inspected_provider_version" = "$inspected_version" ] \
        || fail "installed release provider version is invalid: $selector"
    [ "$(cat "$manifest")" = "$(write_manifest "$inspected_id" \
        "$inspected_version" "$computed_binary_hash" \
        "$computed_deployer_hash" "$computed_chancery_hash")" ] \
        || fail "installed release manifest is invalid: $selector"
}

validate_bundle "$SOURCE_CHANCERY"
candidate_version=$("$binary_path" --version) \
    || fail "unable to read the $DISPLAY_NAME candidate version"
case "$candidate_version" in
    "$BINARY_NAME "*) version=${candidate_version#"$BINARY_NAME "} ;;
    *) fail "candidate reported an unexpected version: $candidate_version" ;;
esac
printf '%s\n' "$version" \
    | grep -Eq '^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$' \
    || fail "candidate reported an invalid version: $version"
provider_release=$(awk -F '"' \
    '/"release"[[:space:]]*:/ { print $4; exit }' \
    "$SOURCE_CHANCERY/provider.json")
[ "$provider_release" = "$version" ] \
    || fail "provider release $provider_release does not match candidate $version"
"$binary_path" --help >/dev/null || fail 'unable to read candidate help'
sh -n "$SOURCE_DEPLOYER"

STATE_DIR="$install_home/Library/Application Support/$APPLICATION_SUPPORT_NAME"
INSTALL_DIR="$STATE_DIR/install"
RELEASES_DIR="$INSTALL_DIR/releases"
CURRENT_LINK="$INSTALL_DIR/current"
PREVIOUS_LINK="$INSTALL_DIR/previous"
UPDATE_LOCK="$INSTALL_DIR/.update-lock"
CLI_DIR="$install_home/.local/bin"
CLI_PATH="$CLI_DIR/$BINARY_NAME"
CHANCERY_STATE="$install_home/Library/Application Support/Chancery"
CHANCERY_PROVIDERS="$CHANCERY_STATE/providers"
CHANCERY_LINK="$CHANCERY_PROVIDERS/$PROVIDER_ID"
CATALOG_LOCK="$CHANCERY_STATE/.catalog-update-lock"
EXPECTED_CLI="$INSTALL_DIR/current/bin/$BINARY_NAME"
EXPECTED_CHANCERY="$INSTALL_DIR/current/share/chancery/$PROVIDER_ID"

for path in "$STATE_DIR" "$INSTALL_DIR" "$RELEASES_DIR"; do
    [ ! -L "$path" ] || fail "refusing symbolic-link directory: $path"
    [ ! -e "$path" ] || [ -d "$path" ] \
        || fail "directory path is occupied by a non-directory: $path"
    install -d -m 0700 "$path"
done

ensure_shared_directory() {
    path=$1
    create_mode=$2
    [ ! -L "$path" ] || fail "refusing symbolic-link directory: $path"
    if [ -e "$path" ]; then
        [ -d "$path" ] \
            || fail "directory path is occupied by a non-directory: $path"
        if shared_uid=$(stat -f '%u' "$path" 2>/dev/null); then
            shared_mode=$(stat -f '%Lp' "$path")
        else
            shared_uid=$(stat -c '%u' "$path")
            shared_mode=$(stat -c '%a' "$path")
        fi
        [ "$shared_uid" = "$operator_uid" ] \
            && [ $((0$shared_mode & 0022)) -eq 0 ] \
            || fail "shared directory ownership or mode is unsafe: $path"
        return
    fi
    install -d -m "$create_mode" "$path"
}

ensure_shared_directory "$CLI_DIR" 0755
ensure_shared_directory "$CHANCERY_STATE" 0700
ensure_shared_directory "$CHANCERY_PROVIDERS" 0700

selected_current() {
    selector_path=$1
    if [ -L "$selector_path" ]; then
        readlink "$selector_path"
    elif [ -e "$selector_path" ]; then
        fail "$selector_path must be a symbolic link"
    else
        printf '%s\n' absent
    fi
}

observed_current=$(selected_current "$CURRENT_LINK")
if [ "$expected_current_set" -eq 0 ]; then
    expected_current=$observed_current
elif [ "$observed_current" != "$expected_current" ]; then
    fail "stale deployment: expected current $expected_current, found $observed_current"
fi

temporary_release=
old_current=
old_previous=
old_cli=
old_provider=
switched=0
committed=0
update_lock_created=0
catalog_lock_created=0
atomic_temporary=

atomic_symlink() {
    target=$1
    path=$2
    temporary="$path.tmp.$$"
    atomic_temporary=$temporary
    rm -f "$temporary"
    ln -s "$target" "$temporary"
    if mv -fh "$temporary" "$path" 2>/dev/null; then
        atomic_temporary=
        return 0
    fi
    mv -fT "$temporary" "$path"
    atomic_temporary=
}

release_owned_lock() {
    lock_path=$1
    if [ -f "$lock_path" ] && [ ! -L "$lock_path" ] \
        && [ "$(sed -n '1p' "$lock_path" 2>/dev/null || true)" = "$$" ]; then
        rm -f "$lock_path" >/dev/null 2>&1 || true
    fi
}

selector_matches() {
    selector_path=$1
    selector_target=$2
    if [ -n "$selector_target" ]; then
        [ -L "$selector_path" ] \
            && [ "$(readlink "$selector_path" 2>/dev/null)" = "$selector_target" ]
    else
        [ ! -e "$selector_path" ] && [ ! -L "$selector_path" ]
    fi
}

cleanup() {
    status=$?
    trap - EXIT HUP INT TERM
    set +e
    if [ "$status" -ne 0 ] && [ "$committed" -eq 0 ] \
        && [ "$switched" -eq 1 ]; then
        rollback_ready=1
        if [ -n "$old_current" ]; then
            atomic_symlink "$old_current" "$CURRENT_LINK" || rollback_ready=0
        else
            rm -f "$CURRENT_LINK" || rollback_ready=0
        fi
        if [ -n "$old_previous" ]; then
            atomic_symlink "$old_previous" "$PREVIOUS_LINK" || rollback_ready=0
        else
            rm -f "$PREVIOUS_LINK" || rollback_ready=0
        fi
        if [ -n "$old_cli" ]; then
            atomic_symlink "$old_cli" "$CLI_PATH" || rollback_ready=0
        else
            rm -f "$CLI_PATH" || rollback_ready=0
        fi
        if [ -n "$old_provider" ]; then
            atomic_symlink "$old_provider" "$CHANCERY_LINK" || rollback_ready=0
        else
            rm -f "$CHANCERY_LINK" || rollback_ready=0
        fi
        selector_matches "$CURRENT_LINK" "$old_current" \
            || rollback_ready=0
        selector_matches "$PREVIOUS_LINK" "$old_previous" \
            || rollback_ready=0
        selector_matches "$CLI_PATH" "$old_cli" || rollback_ready=0
        selector_matches "$CHANCERY_LINK" "$old_provider" \
            || rollback_ready=0
        if [ "$rollback_ready" -eq 0 ]; then
            detach_proven=1
            for selector in "$CLI_PATH" "$CHANCERY_LINK" \
                "$CURRENT_LINK" "$PREVIOUS_LINK"
            do
                rm -f "$selector" || detach_proven=0
                [ ! -e "$selector" ] && [ ! -L "$selector" ] \
                    || detach_proven=0
            done
            if [ "$detach_proven" -eq 1 ]; then
                printf '%s user deploy: rollback could not restore a coherent selector view; public selectors were detached\n' \
                    "$PRODUCT_ID" >&2
            else
                printf '%s user deploy: rollback failed and a detached public selector view could not be proved\n' \
                    "$PRODUCT_ID" >&2
            fi
        fi
    fi
    [ -z "$temporary_release" ] || rm -rf "$temporary_release"
    [ -z "$atomic_temporary" ] || rm -f "$atomic_temporary"
    [ "$catalog_lock_created" -eq 0 ] || release_owned_lock "$CATALOG_LOCK"
    [ "$update_lock_created" -eq 0 ] || release_owned_lock "$UPDATE_LOCK"
    exit "$status"
}
trap cleanup EXIT
trap 'exit 1' HUP INT TERM

acquire_lock() {
    lock_path=$1
    description=$2
    [ ! -L "$lock_path" ] \
        || fail "$description lock is a symbolic link: $lock_path"
    if [ -e "$lock_path" ] && [ ! -f "$lock_path" ]; then
        fail "$description lock is active or not safely recoverable: $lock_path"
    fi
    waited=0
    while ! /usr/bin/shlock -p "$$" -f "$lock_path" >/dev/null 2>&1; do
        [ "$waited" -lt "$lock_wait_seconds" ] \
            || fail "timed out waiting for $description lock: $lock_path"
        sleep 1
        waited=$((waited + 1))
    done
}

update_lock_created=1
acquire_lock "$UPDATE_LOCK" "$DISPLAY_NAME deployment"
locked_current=$(selected_current "$CURRENT_LINK")
[ "$locked_current" = "$expected_current" ] \
    || fail "stale deployment: expected current $expected_current, found $locked_current"

if [ -L "$CURRENT_LINK" ]; then
    old_current=$(readlink "$CURRENT_LINK")
fi
if [ -L "$PREVIOUS_LINK" ]; then
    old_previous=$(readlink "$PREVIOUS_LINK")
elif [ -e "$PREVIOUS_LINK" ]; then
    fail "$PREVIOUS_LINK must be a symbolic link"
fi
if [ -L "$CLI_PATH" ]; then
    old_cli=$(readlink "$CLI_PATH")
elif [ -e "$CLI_PATH" ]; then
    fail "$CLI_PATH exists and is not a symbolic link"
fi
if [ -L "$CHANCERY_LINK" ]; then
    old_provider=$(readlink "$CHANCERY_LINK")
elif [ -e "$CHANCERY_LINK" ]; then
    fail "$CHANCERY_LINK exists and is not a symbolic link"
fi
if [ -n "$old_current" ]; then
    validate_installed_release "$old_current"
    [ "$old_cli" = "$EXPECTED_CLI" ] \
        || fail "command selector is not owned by this installation: $CLI_PATH"
    [ "$old_provider" = "$EXPECTED_CHANCERY" ] \
        || fail "provider selector is not owned by this installation: $CHANCERY_LINK"
    if [ -n "$old_previous" ]; then
        validate_installed_release "$old_previous"
    fi
elif [ -n "$old_previous" ] || [ -n "$old_cli" ] || [ -n "$old_provider" ]; then
    fail "installed selectors have no current $DISPLAY_NAME release"
fi

binary_hash=$(shasum -a 256 "$binary_path" | awk '{print $1}')
deployer_hash=$(shasum -a 256 "$SOURCE_DEPLOYER" | awk '{print $1}')
chancery_hash=$(bundle_hash "$SOURCE_CHANCERY")
release_id=$(printf '%s\n' "$binary_hash" "$deployer_hash" "$chancery_hash" \
    | shasum -a 256 | awk '{print $1}')
release_path="$RELEASES_DIR/$release_id"

if [ -L "$release_path" ]; then
    fail "existing release must not be a symbolic link: $release_id"
elif [ -e "$release_path" ] && [ ! -d "$release_path" ]; then
    fail "existing release is not a directory: $release_id"
fi
if [ -d "$release_path" ]; then
    validate_installed_release "releases/$release_id"
else
    temporary_release=$(mktemp -d "$RELEASES_DIR/.stage.XXXXXX")
    install -d -m 0755 "$temporary_release/bin" \
        "$temporary_release/package" "$temporary_release/share" \
        "$temporary_release/share/chancery"
    install -m 0755 "$binary_path" "$temporary_release/bin/$BINARY_NAME"
    install -m 0755 "$SOURCE_DEPLOYER" \
        "$temporary_release/package/deploy-user.sh"
    cp -R "$SOURCE_CHANCERY" \
        "$temporary_release/share/chancery/$PROVIDER_ID"
    write_manifest "$release_id" "$version" "$binary_hash" \
        "$deployer_hash" "$chancery_hash" >"$temporary_release/manifest.txt"
    chmod 0444 "$temporary_release/manifest.txt"
    mv "$temporary_release" "$release_path"
    temporary_release=
    validate_installed_release "releases/$release_id"
fi

if [ "$old_current" != "releases/$release_id" ]; then
    catalog_lock_created=1
    acquire_lock "$CATALOG_LOCK" 'Chancery catalog writer'
    catalog_current=$(selected_current "$CURRENT_LINK")
    [ "$catalog_current" = "$expected_current" ] \
        || fail "stale deployment: expected current $expected_current, found $catalog_current"

    switched=1
    if [ -n "$old_current" ]; then
        atomic_symlink "$old_current" "$PREVIOUS_LINK"
        atomic_symlink "releases/$release_id" "$CURRENT_LINK"
    else
        atomic_symlink "$EXPECTED_CLI" "$CLI_PATH"
        atomic_symlink "$EXPECTED_CHANCERY" "$CHANCERY_LINK"
        atomic_symlink "releases/$release_id" "$CURRENT_LINK"
    fi
fi

installed_version=$(HOME="$install_home" "$CLI_PATH" --version) \
    || fail "installed $DISPLAY_NAME version check failed"
[ "$installed_version" = "$BINARY_NAME $version" ] \
    || fail "installed $DISPLAY_NAME reported an unexpected version: $installed_version"
HOME="$install_home" "$CLI_PATH" --help >/dev/null \
    || fail "installed $DISPLAY_NAME help check failed"
[ -f "$CHANCERY_LINK/provider.json" ] \
    || fail "installed $DISPLAY_NAME Chancery provider is unavailable"
validate_installed_release "$(readlink "$CURRENT_LINK")"

committed=1
printf 'Installed %s release %s\n' "$DISPLAY_NAME" "$release_id"
printf 'Command: %s\n' "$CLI_PATH"
[ "$PRINT_STATE_PATH" -eq 0 ] || printf 'State:   %s\n' "$STATE_DIR"
printf 'Chancery provider: %s\n' "$CHANCERY_LINK"
[ -z "$COMPLETION_NOTE" ] || printf '%s\n' "$COMPLETION_NOTE"
