#!/usr/bin/env python3
"""Repository-facing client for the Cell CI broker."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import platform
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Sequence

try:
    import pwd
except ImportError:  # pragma: no cover - the CI body gate is POSIX-only
    pwd = None  # type: ignore[assignment]

# Keep generated bytecode out of the candidate worktree.
sys.dont_write_bytecode = True

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from ci_broker import broker
from ci_manager import workspace


DEFAULT_CARGO_JOBS = 2


def canonical_state_dir() -> Path:
    """Return the one production journal location for the current user."""

    return workspace.directory("ci-broker")


def bootstrap_cargo_path() -> None:
    """Match the product gates' existing rustup PATH bootstrap."""

    if shutil.which("cargo") is not None and shutil.which("rustc") is not None:
        return
    cargo_home = os.environ.get("CARGO_HOME")
    if cargo_home is None:
        home = os.environ.get("HOME")
        if home:
            cargo_home = str(Path(home) / ".cargo")
    candidates = [Path(cargo_home).expanduser() / "bin"] if cargo_home else []
    if pwd is not None:
        candidates.append(Path(pwd.getpwuid(os.getuid()).pw_dir) / ".cargo/bin")
    for cargo_bin in candidates:
        if not (cargo_bin / "cargo").is_file():
            continue
        existing = os.environ.get("PATH")
        os.environ["PATH"] = os.pathsep.join(
            part for part in (str(cargo_bin), existing) if part
        )
        return


def git(repository: Path, *arguments: str) -> bytes:
    try:
        result = subprocess.run(
            ("git", "-C", str(repository), *arguments),
            check=False,
            capture_output=True,
            timeout=30,
        )
    except (OSError, subprocess.SubprocessError) as error:
        raise broker.BrokerError(f"cannot inspect Git repository: {error}") from error
    if result.returncode != 0:
        message = result.stderr.decode("utf-8", "replace").strip()
        raise broker.BrokerError(message or "Git repository inspection failed")
    return result.stdout


def repository_root(path: Path) -> Path:
    raw = git(path, "rev-parse", "--show-toplevel").decode("utf-8", "strict").strip()
    root = Path(raw).resolve()
    if not root.is_dir():
        raise broker.BrokerError(f"Git worktree root does not exist: {root}")
    return root


def common_git_directory(root: Path) -> Path:
    try:
        raw = git(
            root, "rev-parse", "--path-format=absolute", "--git-common-dir"
        ).decode("utf-8", "strict").strip()
        common = Path(raw)
    except broker.BrokerError:
        raw = git(root, "rev-parse", "--git-common-dir").decode(
            "utf-8", "strict"
        ).strip()
        common = Path(raw)
        if not common.is_absolute():
            common = root / common
    common = common.resolve()
    if not common.is_dir():
        raise broker.BrokerError(f"Git common directory does not exist: {common}")
    return common


def logical_repository_id(common: Path) -> str:
    identity = hashlib.sha256(os.fsencode(str(common.resolve()))).hexdigest()
    return f"git-common-sha256:{identity}"


def source_commit(root: Path) -> str:
    return git(root, "rev-parse", "--verify", "HEAD^{commit}").decode("ascii").strip()


def repository_is_clean(root: Path) -> bool:
    return not git(
        root,
        "status",
        "--porcelain=v1",
        "-z",
        "--untracked-files=all",
        "--ignore-submodules=none",
    )


def toolchain_key() -> str:
    facts: dict[str, str] = {
        "platform": platform.platform(),
        "python": sys.version,
    }
    for command, arguments in (("git", ("--version",)), ("cargo", ("-Vv",)), ("rustc", ("-vV",))):
        executable = shutil.which(command)
        if executable is None:
            raise broker.BrokerError(f"required toolchain command is unavailable: {command}")
        try:
            result = subprocess.run(
                (executable, *arguments),
                check=False,
                capture_output=True,
                text=True,
                timeout=30,
            )
        except (OSError, subprocess.SubprocessError) as error:
            raise broker.BrokerError(f"cannot identify {command}: {error}") from error
        if result.returncode != 0:
            raise broker.BrokerError(f"cannot identify {command} toolchain")
        facts[f"{command}_path"] = str(Path(executable).resolve())
        facts[f"{command}_version"] = result.stdout.strip()
    return f"sha256:{broker.digest_json(facts)}"


def cargo_jobs() -> int:
    raw = os.environ.get("CELL_CI_CARGO_JOBS", str(DEFAULT_CARGO_JOBS))
    try:
        jobs = int(raw)
    except ValueError as error:
        raise broker.BrokerError("CELL_CI_CARGO_JOBS must be a positive integer") from error
    if jobs < 1:
        raise broker.BrokerError("CELL_CI_CARGO_JOBS must be a positive integer")
    return jobs


def execution_toolchain(gate: str, command: list[str]) -> str:
    key = toolchain_key()
    if gate != "cell.tests.rust":
        return key
    from pipeline import nextest_tool
    try:
        selected = Path(command[command.index("--nextest-path") + 1])
        runner = nextest_tool.identity(selected)
    except (ValueError, IndexError, OSError) as error:
        raise broker.BrokerError(f"cannot identify nextest: {error}") from error
    return "sha256:" + broker.digest_json({"compiler": key, "nextest": runner})


def client_parser() -> argparse.ArgumentParser:
    root = argparse.ArgumentParser(description=__doc__)
    commands = root.add_subparsers(dest="subcommand", required=True)

    run = commands.add_parser("run", help="run one repository CI body through the broker")
    run.add_argument("--gate", required=True)
    run.add_argument("--lane", choices=("heavy", "light"), default="heavy")
    run.add_argument("--gate-version")
    run.add_argument(
        "--expected-source-key",
        help="bind this gate to the commit captured by an enclosing root plan",
    )
    run.add_argument("--repo-root", default=os.getcwd())
    run.add_argument("--cwd")
    run.add_argument("--full-environment", action="store_true")
    run.add_argument("--inherit-env", action="append", default=[])
    run.add_argument("--env", action="append", default=[])
    run.add_argument("--unset-env", action="append", default=[])
    run.add_argument("--attribution-json")
    run.add_argument("--verbose", action="store_true", help="show the body transcript")
    run.add_argument("--quiet-result", action="store_true", help="omit a passed result line")
    run.add_argument(
        "--verbose-receipt",
        action="store_true",
        help="print the complete JSON receipt instead of a text result",
    )
    run.add_argument("command", nargs=argparse.REMAINDER)

    source = commands.add_parser("source-key", help="print the current HEAD commit")
    source.add_argument("--repo-root", default=os.getcwd())
    source.add_argument("--show-clean", action="store_true")

    status = commands.add_parser("status", help="read one durable execution receipt")
    add_client_scope_arguments(status)
    status.add_argument("--events", action="store_true")
    status.add_argument("execution_id")

    recover = commands.add_parser("recover", help="recover abandoned broker work")
    add_client_scope_arguments(recover)
    return root


def add_client_scope_arguments(command: argparse.ArgumentParser) -> None:
    command.add_argument("--repo-root", default=os.getcwd())


def broker_scope_arguments(arguments: argparse.Namespace) -> list[str]:
    root = repository_root(Path(arguments.repo_root).expanduser().resolve())
    common = common_git_directory(root)
    return [
        "--repo-id",
        logical_repository_id(common),
        "--host-id",
        broker.default_host_id(),
        "--state-dir",
        str(canonical_state_dir()),
        "--light-slots",
        str(broker.DEFAULT_LIGHT_SLOTS),
        "--cargo-jobs",
        str(cargo_jobs()),
        "--heartbeat-timeout",
        str(broker.DEFAULT_HEARTBEAT_TIMEOUT),
        "--poll-interval",
        str(broker.DEFAULT_POLL_INTERVAL),
    ]


def run(arguments: argparse.Namespace) -> int:
    bootstrap_cargo_path()
    root = repository_root(Path(arguments.repo_root).expanduser().resolve())
    common = common_git_directory(root)
    cwd = (
        Path(arguments.cwd).expanduser().resolve()
        if arguments.cwd is not None
        else root
    )
    try:
        cwd.relative_to(root)
    except ValueError as error:
        raise broker.BrokerError("CI body working directory must be inside the worktree") from error
    if not cwd.is_dir():
        raise broker.BrokerError(f"CI body working directory does not exist: {cwd}")

    command = broker.strip_separator(arguments.command)
    current_source_key = source_commit(root)
    expected_source_key = (
        arguments.expected_source_key
        if arguments.expected_source_key is not None
        else os.environ.get("CELL_CI_EXPECTED_SOURCE_KEY")
    )
    source_key = (
        broker.require_text("--expected-source-key", expected_source_key)
        if expected_source_key is not None
        else current_source_key
    )
    if expected_source_key is not None and current_source_key != source_key:
        if arguments.verbose_receipt:
            print(json.dumps({
                    "protocol_version": broker.PROTOCOL_VERSION,
                    "execution_id": None,
                    "state": "stale",
                    "execution_state": "stale",
                    "gate": arguments.gate,
                    "source_key": source_key,
                    "observed_source_key": current_source_key,
                    "detail": "expected commit does not match HEAD",
                }, sort_keys=True))
        else:
            print(
                f"ci: {arguments.gate} stale; expected commit does not match HEAD",
                file=sys.stderr,
            )
        return 75
    jobs = cargo_jobs()
    gate_version = arguments.gate_version
    if gate_version is None:
        relative_cwd = cwd.relative_to(root).as_posix() or "."
        gate_version = "sha256:" + broker.digest_json(
            {
                "gate": arguments.gate,
                "source_key": source_key,
                "command": broker.normalize_argv(command, root),
                "cwd": relative_cwd,
                "protocol_version": broker.PROTOCOL_VERSION,
            }
        )
    workspace.require_capacity()
    work_environment = workspace.environment()
    target = workspace.directory("targets/" + logical_repository_id(common).split(":")[1])

    broker_arguments = [
        "run",
        "--repo-id",
        logical_repository_id(common),
        "--host-id",
        broker.default_host_id(),
        "--state-dir",
        str(canonical_state_dir()),
        "--light-slots",
        str(broker.DEFAULT_LIGHT_SLOTS),
        "--cargo-jobs",
        str(jobs),
        "--heartbeat-timeout",
        str(broker.DEFAULT_HEARTBEAT_TIMEOUT),
        "--poll-interval",
        str(broker.DEFAULT_POLL_INTERVAL),
        "--source-key",
        source_key,
        "--gate",
        arguments.gate,
        "--gate-version",
        gate_version,
        "--toolchain-key",
        execution_toolchain(arguments.gate, command),
        "--lane",
        arguments.lane,
        "--cwd",
        str(cwd),
        "--identity-root",
        str(root),
        "--environment-mode",
        "full" if arguments.full_environment else "minimal",
        "--env",
        f"CARGO_TARGET_DIR={target}",
        "--env",
        "CARGO_INCREMENTAL=0",
        "--unset-env",
        "CELL_CI_CARGO_JOBS",
    ]
    for name in arguments.inherit_env:
        broker_arguments.extend(("--inherit-env", name))
    for assignment in arguments.env:
        broker_arguments.extend(("--env", assignment))
    for name in arguments.unset_env:
        if name in work_environment or name in {"CARGO_TARGET_DIR", "CARGO_BUILD_BUILD_DIR"}:
            raise broker.BrokerError(f"cannot unset infrastructure storage setting: {name}")
        broker_arguments.extend(("--unset-env", name))
    # Storage routing is infrastructure-owned, after caller environment options.
    for name, value in {**work_environment, "CARGO_TARGET_DIR": str(target),
                        "CARGO_BUILD_BUILD_DIR": str(target)}.items():
        broker_arguments.extend(("--env", f"{name}={value}"))
    command = workspace.confined_command(command)
    if arguments.attribution_json is not None:
        broker_arguments.extend(("--attribution-json", arguments.attribution_json))
    if repository_is_clean(root) and current_source_key == source_key:
        broker_arguments.append("--share-clean-candidate")
    if arguments.verbose_receipt:
        broker_arguments.append("--verbose-receipt")
    if arguments.verbose:
        broker_arguments.append("--verbose")
    if arguments.quiet_result:
        broker_arguments.append("--quiet-result")
    broker_arguments.extend(("--", *command))
    return broker.main(broker_arguments)


def source_key_command(arguments: argparse.Namespace) -> int:
    root = repository_root(Path(arguments.repo_root).expanduser().resolve())
    key = source_commit(root)
    if arguments.show_clean:
        print(json.dumps({"clean": repository_is_clean(root), "source_key": key}, sort_keys=True))
    else:
        print(key)
    return 0


def status_command(arguments: argparse.Namespace) -> int:
    command = ["status", *broker_scope_arguments(arguments)]
    if arguments.events:
        command.append("--events")
    command.append(arguments.execution_id)
    return broker.main(command)


def recover_command(arguments: argparse.Namespace) -> int:
    return broker.main(["recover", *broker_scope_arguments(arguments)])


def main(argv: Sequence[str] | None = None) -> int:
    arguments = client_parser().parse_args(argv)
    try:
        if arguments.subcommand == "run":
            return run(arguments)
        if arguments.subcommand == "source-key":
            return source_key_command(arguments)
        if arguments.subcommand == "status":
            return status_command(arguments)
        if arguments.subcommand == "recover":
            return recover_command(arguments)
        raise broker.BrokerError(f"unsupported subcommand: {arguments.subcommand}")
    except (broker.BrokerError, workspace.WorkspaceError, OSError, subprocess.SubprocessError) as error:
        print(f"cell-ci: broker error: {error}", file=sys.stderr)
        return 78


if __name__ == "__main__":
    raise SystemExit(main())
