#!/bin/sh
# Generated by pipeline/generate.sh from pipeline/products/geste.sh.
# This publishes a release; it is not a build command.
set -eu
PRODUCT_DIR=$(CDPATH='' cd "$(dirname "$0")" && pwd)
CELL_ROOT=$(CDPATH='' cd "$PRODUCT_DIR/.." && pwd)
exec "$CELL_ROOT/pipeline/release.sh" "geste" "$@"
