//! Codex app-server adapter for Nucleus.
//!
//! This crate deliberately exposes Nucleus's small invocation domain instead of
//! Codex command-line arguments. The adapter owns the translation to a concrete,
//! inspected Codex installation.

use std::collections::BTreeSet;
use std::ffi::OsStr;
use std::future;
use std::io;
use std::os::unix::process::CommandExt as _;
use std::path::{Path, PathBuf};
use std::process::{Command as StdCommand, Stdio};
use std::time::Duration;

use serde::{Deserialize, Serialize};
use serde_json::{Value, json};
use tempfile::TempDir;
use thiserror::Error;
use tokio::io::{AsyncBufReadExt as _, AsyncReadExt as _, AsyncWriteExt as _, BufReader};
use tokio::process::{Child, ChildStdin, Command};
use tokio::sync::{mpsc, oneshot, watch};
use tokio::task::JoinHandle;

pub use nucleus_core::{BuiltinToolsV1, WorkspaceAccess};

const MAX_PROTOCOL_BYTES: u64 = 256 * 1024 * 1024;
const MAX_MODEL_CATALOG_BYTES: usize = 8 * 1024 * 1024;
const STDERR_CHUNK_BYTES: usize = 8 * 1024;
const SHUTDOWN_GRACE: Duration = Duration::from_secs(3);

/// The exact Codex CLI release whose app-server contract this adapter proves.
/// Supporting another release requires reviewing and updating the protocol
/// semantic checks below.
pub const SUPPORTED_CODEX_VERSION: &str = "0.146.0";

const DISABLED_FEATURES: &[&str] = &[
    "apps",
    "auth_elicitation",
    "browser_use",
    "browser_use_external",
    "browser_use_full_cdp_access",
    "computer_use",
    "deferred_executor",
    "enable_mcp_apps",
    "goals",
    "image_generation",
    "in_app_browser",
    "multi_agent",
    "multi_agent_v2",
    "plugins",
    "remote_plugin",
    "request_permissions_tool",
    "skill_mcp_dependency_install",
    "skill_search",
    "token_budget",
    "tool_call_mcp_elicitation",
    "tool_suggest",
];

const CONFIG_OVERRIDES: &[&str] = &[
    "agents.enabled=false",
    "cli_auth_credentials_store=\"file\"",
    "include_apps_instructions=false",
    "include_collaboration_mode_instructions=false",
    "orchestrator.mcp.enabled=false",
    "orchestrator.skills.enabled=false",
    "skills.bundled.enabled=false",
    "skills.include_instructions=false",
    "tools.experimental_request_user_input.enabled=false",
    "tools.update_plan.enabled=false",
];

/// The directions in which raw app-server protocol records travel.
#[derive(Debug, Clone, Copy, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ProtocolDirection {
    ToHarness,
    FromHarness,
}

/// One requester-owned dynamic tool exposed to Codex.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DynamicTool {
    pub name: String,
    pub description: String,
    pub input_schema: Value,
}

/// The stable settings accepted by the Codex adapter.
#[derive(Debug, Clone)]
pub struct CodexRunSpec {
    pub instructions: String,
    pub prompt: String,
    pub model: String,
    pub reasoning_effort: Option<String>,
    pub working_directory: PathBuf,
    pub workspace_access: WorkspaceAccess,
    pub builtin_tools: BuiltinToolsV1,
    pub timeout: Duration,
    pub tools: Vec<DynamicTool>,
}

/// Exact installed-harness identity and the capabilities used for validation.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct HarnessInspection {
    pub harness: String,
    pub version: String,
    pub executable: PathBuf,
    pub models: Vec<ModelCapability>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ModelCapability {
    pub model: String,
    pub default_reasoning_effort: Option<String>,
    pub reasoning_efforts: Vec<String>,
    pub supports_local_execution: bool,
    pub supports_web_search: bool,
}

/// Opaque external schema generated by the exact Codex binary.
#[derive(Debug, Clone)]
pub struct GeneratedSchema {
    pub media_type: &'static str,
    pub bytes: Vec<u8>,
}

/// Events are ordered as observed by the adapter. Protocol records retain their
/// exact JSONL bytes, including the line terminator.
#[derive(Debug)]
pub enum CodexEvent {
    Protocol {
        direction: ProtocolDirection,
        bytes: Vec<u8>,
    },
    Stderr(Vec<u8>),
    ToolCall(PendingToolCall),
}

#[derive(Debug)]
pub struct PendingToolCall {
    pub call_id: String,
    pub name: String,
    pub arguments: Value,
    pub reply: oneshot::Sender<ToolResult>,
}

/// The requester service returns this value through the Nucleus mailbox.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ToolResult {
    pub success: bool,
    /// JSON or prose presented to the model as one input-text content item.
    pub content: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CodexOutcome {
    pub thread_id: String,
    pub turn_id: String,
    pub final_message: String,
}

#[derive(Debug, Error)]
pub enum CodexError {
    #[error("Codex harness inspection failed: {0}")]
    Inspection(String),
    #[error("unsupported invocation setting {setting}: {reason}")]
    UnsupportedSetting { setting: String, reason: String },
    #[error("could not prepare isolated Codex state: {0}")]
    Preparation(#[source] io::Error),
    #[error("could not start Codex app-server: {0}")]
    Spawn(#[source] io::Error),
    #[error("Codex app-server protocol failed: {0}")]
    Protocol(String),
    #[error("the durable event consumer disconnected")]
    EventConsumerDisconnected,
    #[error("job cancelled")]
    Cancelled,
    #[error("job exceeded its timeout")]
    TimedOut,
    #[error("Codex turn ended with status {status}: {detail}")]
    TurnFailed { status: String, detail: String },
}

#[derive(Debug, Clone)]
pub struct CodexHarness {
    executable: PathBuf,
}

impl Default for CodexHarness {
    fn default() -> Self {
        Self::new("codex")
    }
}

impl CodexHarness {
    #[must_use]
    pub fn new(executable: impl Into<PathBuf>) -> Self {
        Self {
            executable: executable.into(),
        }
    }

    #[must_use]
    pub fn executable(&self) -> &Path {
        &self.executable
    }

    /// Inspect the exact binary used to execute jobs. Validation never assumes
    /// that a model or effort supported by another Codex version is available.
    ///
    /// # Errors
    ///
    /// Returns an inspection error when the executable cannot be run or its
    /// version/model-catalog output is unsuccessful or malformed.
    pub async fn inspect(&self) -> Result<HarnessInspection, CodexError> {
        let version = self.read_version().await?;

        let catalog_output = self
            .command()
            .args(["debug", "models", "--bundled"])
            .output()
            .await
            .map_err(|error| CodexError::Inspection(error.to_string()))?;
        if !catalog_output.status.success() {
            return Err(CodexError::Inspection(diagnostic(
                "could not read Codex's bundled model catalog",
                &catalog_output.stderr,
            )));
        }
        if catalog_output.stdout.len() > MAX_MODEL_CATALOG_BYTES {
            return Err(CodexError::Inspection(format!(
                "Codex's bundled model catalog exceeded {MAX_MODEL_CATALOG_BYTES} bytes"
            )));
        }
        let catalog: Value = serde_json::from_slice(&catalog_output.stdout)
            .map_err(|error| CodexError::Inspection(format!("invalid model catalog: {error}")))?;
        let entries = catalog
            .get("models")
            .and_then(Value::as_array)
            .ok_or_else(|| CodexError::Inspection("model catalog omitted models".to_owned()))?;
        let mut models = Vec::with_capacity(entries.len());
        for entry in entries {
            let Some(model) = entry.get("slug").and_then(Value::as_str) else {
                continue;
            };
            let reasoning_efforts = entry
                .get("supported_reasoning_levels")
                .and_then(Value::as_array)
                .into_iter()
                .flatten()
                .filter_map(|level| level.get("effort").and_then(Value::as_str))
                .map(str::to_owned)
                .collect();
            let default_reasoning_effort = entry
                .get("default_reasoning_level")
                .and_then(Value::as_str)
                .map(str::to_owned);
            let supports_local_execution = entry
                .get("shell_type")
                .and_then(Value::as_str)
                .is_some_and(|kind| kind != "disabled");
            let supports_web_search = entry
                .get("supports_search_tool")
                .and_then(Value::as_bool)
                .unwrap_or(false);
            models.push(ModelCapability {
                model: model.to_owned(),
                default_reasoning_effort,
                reasoning_efforts,
                supports_local_execution,
                supports_web_search,
            });
        }
        if models.is_empty() {
            return Err(CodexError::Inspection(
                "model catalog contained no usable models".to_owned(),
            ));
        }
        Ok(HarnessInspection {
            harness: "codex".to_owned(),
            version,
            executable: self.executable.clone(),
            models,
        })
    }

    async fn read_version(&self) -> Result<String, CodexError> {
        let output = self
            .command()
            .arg("--version")
            .output()
            .await
            .map_err(|error| CodexError::Inspection(error.to_string()))?;
        if !output.status.success() {
            return Err(CodexError::Inspection(diagnostic(
                "codex --version failed",
                &output.stderr,
            )));
        }
        let line = String::from_utf8_lossy(&output.stdout).trim().to_owned();
        let version = line.strip_prefix("codex-cli ").unwrap_or(&line).to_owned();
        if version.is_empty() {
            Err(CodexError::Inspection(
                "codex --version returned an empty version".to_owned(),
            ))
        } else {
            Ok(version)
        }
    }

    /// Ask the installed harness to emit its protocol schema. The resulting
    /// document is stored opaquely by Nucleus and referenced by each JSONL row.
    ///
    /// # Errors
    ///
    /// Returns an error when schema generation fails or the generated bundle
    /// cannot be read.
    pub async fn generate_protocol_schema(&self) -> Result<GeneratedSchema, CodexError> {
        let directory = TempDir::new().map_err(CodexError::Preparation)?;
        let output = self
            .command()
            .args([
                "app-server",
                "generate-json-schema",
                "--experimental",
                "--out",
            ])
            .arg(directory.path())
            .output()
            .await
            .map_err(|error| CodexError::Inspection(error.to_string()))?;
        if !output.status.success() {
            return Err(CodexError::Inspection(diagnostic(
                "Codex schema generation failed",
                &output.stderr,
            )));
        }
        let path = directory
            .path()
            .join("codex_app_server_protocol.schemas.json");
        let bytes = tokio::fs::read(path)
            .await
            .map_err(CodexError::Preparation)?;
        Ok(GeneratedSchema {
            media_type: "application/schema+json",
            bytes,
        })
    }

    /// Validate the complete portable run specification against one inspected
    /// Codex installation.
    ///
    /// # Errors
    ///
    /// Returns [`CodexError::UnsupportedSetting`] for every setting the exact
    /// inspected harness cannot enforce.
    pub fn validate(
        &self,
        inspection: &HarnessInspection,
        spec: &CodexRunSpec,
    ) -> Result<(), CodexError> {
        self.validate_inspection_identity(inspection)?;
        if !spec.working_directory.is_absolute() {
            return Err(unsupported("workingDirectory", "must be an absolute path"));
        }
        if !spec.working_directory.is_dir() {
            return Err(unsupported(
                "workingDirectory",
                "must name an existing directory",
            ));
        }
        if spec.timeout.is_zero() {
            return Err(unsupported("timeoutSeconds", "must be greater than zero"));
        }
        if std::time::Instant::now()
            .checked_add(spec.timeout)
            .is_none()
        {
            return Err(unsupported(
                "timeoutSeconds",
                "is too large for this platform's monotonic clock",
            ));
        }
        if spec.builtin_tools.local_execution
            && matches!(spec.workspace_access, WorkspaceAccess::None)
        {
            return Err(unsupported(
                "builtinTools.localExecution",
                "the Codex adapter cannot guarantee local execution with no filesystem access",
            ));
        }
        let model = inspection
            .models
            .iter()
            .find(|candidate| candidate.model == spec.model)
            .ok_or_else(|| {
                unsupported(
                    "model",
                    format!(
                        "{} is not in Codex {}'s bundled catalog",
                        spec.model, inspection.version
                    ),
                )
            })?;
        if let Some(requested_effort) = &spec.reasoning_effort
            && !model
                .reasoning_efforts
                .iter()
                .any(|effort| effort == requested_effort)
        {
            return Err(unsupported(
                "reasoningEffort",
                format!(
                    "{} does not support {:?} in Codex {}",
                    spec.model, requested_effort, inspection.version
                ),
            ));
        }
        if spec.builtin_tools.local_execution && !model.supports_local_execution {
            return Err(unsupported(
                "builtinTools.localExecution",
                format!(
                    "{} does not support local execution in Codex {}",
                    spec.model, inspection.version
                ),
            ));
        }
        if spec.builtin_tools.web_search && !model.supports_web_search {
            return Err(unsupported(
                "builtinTools.webSearch",
                format!(
                    "{} does not support web search in Codex {}",
                    spec.model, inspection.version
                ),
            ));
        }
        validate_tools(&spec.tools)
    }

    /// Verify that the generated schema for the inspected binary contains the
    /// exact app-server semantics used by the v1 adapter.
    ///
    /// This is intentionally structural rather than a schema digest allowlist:
    /// unrelated additions to Codex's generated bundle do not break admission,
    /// while removal or renaming of anything Nucleus sends or consumes does.
    ///
    /// # Errors
    ///
    /// Returns an unsupported-setting error for an unbound harness version or
    /// an app-server schema missing any required v1 protocol semantic.
    pub fn validate_protocol_schema(
        &self,
        inspection: &HarnessInspection,
        schema: &GeneratedSchema,
    ) -> Result<(), CodexError> {
        self.validate_inspection_identity(inspection)?;
        let document: Value = serde_json::from_slice(&schema.bytes).map_err(|error| {
            incompatible_protocol(format!("generated schema is not JSON: {error}"))
        })?;
        verify_protocol_semantics(&document)
    }

    fn validate_inspection_identity(
        &self,
        inspection: &HarnessInspection,
    ) -> Result<(), CodexError> {
        if inspection.harness != "codex" {
            return Err(unsupported(
                "harness",
                "the Codex adapter only accepts codex",
            ));
        }
        if inspection.executable != self.executable {
            return Err(unsupported(
                "harness",
                "the inspected executable does not match this adapter instance",
            ));
        }
        if inspection.version != SUPPORTED_CODEX_VERSION {
            return Err(unsupported(
                "harness.version",
                format!(
                    "Codex {} is not bound to this adapter; supported version is {SUPPORTED_CODEX_VERSION}",
                    inspection.version
                ),
            ));
        }
        Ok(())
    }

    async fn write_model_catalog(
        &self,
        directory: &Path,
        codex_home: &Path,
        spec: &CodexRunSpec,
    ) -> Result<PathBuf, CodexError> {
        let mut command = self.command();
        command
            .args(["debug", "models", "--bundled"])
            .env("CODEX_HOME", codex_home)
            .stdin(Stdio::null())
            .stderr(Stdio::piped())
            .kill_on_drop(true);
        let output = command
            .output()
            .await
            .map_err(|error| CodexError::Inspection(error.to_string()))?;
        if !output.status.success() {
            return Err(CodexError::Inspection(diagnostic(
                "could not read Codex's bundled model catalog",
                &output.stderr,
            )));
        }
        if output.stdout.len() > MAX_MODEL_CATALOG_BYTES {
            return Err(CodexError::Inspection(format!(
                "Codex's bundled model catalog exceeded {MAX_MODEL_CATALOG_BYTES} bytes"
            )));
        }
        let catalog = configured_model_catalog(&output.stdout, spec)?;
        let path = directory.join("models.json");
        tokio::fs::write(
            &path,
            serde_json::to_vec(&catalog).map_err(|error| {
                CodexError::Protocol(format!("could not encode model catalog: {error}"))
            })?,
        )
        .await
        .map_err(CodexError::Preparation)?;
        Ok(path)
    }

    /// Run one ephemeral Codex thread. The caller must durably consume every
    /// event; disconnecting the event channel fails the run.
    ///
    /// # Errors
    ///
    /// Returns an error for validation, preparation, protocol, tool-mailbox,
    /// cancellation, timeout, or harness-turn failure. The harness process group
    /// is cleaned up before ordinary return and by a drop guard if aborted.
    pub async fn run(
        &self,
        inspection: &HarnessInspection,
        spec: CodexRunSpec,
        events: mpsc::Sender<CodexEvent>,
        mut cancelled: watch::Receiver<bool>,
    ) -> Result<CodexOutcome, CodexError> {
        self.validate(inspection, &spec)?;
        let deadline = tokio::time::Instant::now()
            .checked_add(spec.timeout)
            .ok_or_else(|| unsupported("timeoutSeconds", "cannot represent deadline"))?;
        let temporary = TempDir::new().map_err(CodexError::Preparation)?;
        let codex_home = temporary.path().join("codex-home");
        tokio::fs::create_dir(&codex_home)
            .await
            .map_err(CodexError::Preparation)?;
        copy_codex_auth(&codex_home).await?;
        let catalog_path = {
            let preparation = async {
                let current_version = self.read_version().await?;
                if current_version != inspection.version {
                    return Err(CodexError::Inspection(format!(
                        "Codex changed from version {} to {current_version} after admission",
                        inspection.version
                    )));
                }
                self.write_model_catalog(temporary.path(), &codex_home, &spec)
                    .await
            };
            tokio::pin!(preparation);
            let cancellation = wait_for_cancellation(&mut cancelled);
            tokio::pin!(cancellation);
            tokio::select! {
                result = &mut preparation => result?,
                () = &mut cancellation => return Err(CodexError::Cancelled),
                () = tokio::time::sleep_until(deadline) => return Err(CodexError::TimedOut),
            }
        };

        let effective_cwd = match spec.workspace_access {
            WorkspaceAccess::None => {
                let path = temporary.path().join("workspace");
                tokio::fs::create_dir(&path)
                    .await
                    .map_err(CodexError::Preparation)?;
                path
            }
            WorkspaceAccess::ReadOnly | WorkspaceAccess::ReadWrite => {
                spec.working_directory.clone()
            }
        };

        let mut command =
            self.app_server_command(&spec, &effective_cwd, &codex_home, &catalog_path)?;

        let mut child = command.spawn().map_err(CodexError::Spawn)?;
        let group = child.id();
        // Tokio's `kill_on_drop` targets only the direct child. The guard also
        // kills its process group if this future is aborted mid-run.
        let mut process_group = ProcessGroupGuard::new(group);
        let stdin = child
            .stdin
            .take()
            .ok_or_else(|| CodexError::Protocol("app-server did not expose stdin".to_owned()))?;
        let stdout = child
            .stdout
            .take()
            .ok_or_else(|| CodexError::Protocol("app-server did not expose stdout".to_owned()))?;
        let stderr = child
            .stderr
            .take()
            .ok_or_else(|| CodexError::Protocol("app-server did not expose stderr".to_owned()))?;

        let (lines_tx, lines_rx) = mpsc::channel(64);
        let stdout_task = tokio::spawn(read_protocol_lines(stdout, lines_tx, events.clone()));
        let stderr_task = tokio::spawn(read_stderr(stderr, events.clone()));
        let result = {
            let protocol = ProtocolClient {
                stdin,
                lines: lines_rx,
                events: events.clone(),
                next_request_id: 0,
                final_message: String::new(),
                active_thread_id: None,
                active_turn_id: None,
                allowed_tools: spec.tools.iter().map(|tool| tool.name.clone()).collect(),
                seen_tool_calls: BTreeSet::new(),
            }
            .run(&spec, &effective_cwd);
            tokio::pin!(protocol);

            let timeout = tokio::time::sleep_until(deadline);
            tokio::pin!(timeout);
            let cancellation = wait_for_cancellation(&mut cancelled);
            tokio::pin!(cancellation);

            tokio::select! {
                result = &mut protocol => result,
                () = &mut cancellation => Err(CodexError::Cancelled),
                () = &mut timeout => Err(CodexError::TimedOut),
            }
        };

        terminate_process_group(&mut child, &mut process_group).await;
        let stdout_result = join_reader(stdout_task, "stdout").await;
        let stderr_result = join_reader(stderr_task, "stderr").await;
        drop(events);

        stdout_result?;
        stderr_result?;
        result
    }

    fn command(&self) -> Command {
        let mut command = Command::new(&self.executable);
        command
            .env_remove("CODEX_EXEC_SERVER_URL")
            .kill_on_drop(true);
        command
    }

    fn app_server_command(
        &self,
        spec: &CodexRunSpec,
        effective_cwd: &Path,
        codex_home: &Path,
        catalog_path: &Path,
    ) -> Result<Command, CodexError> {
        let mut command = self.command();
        for feature in DISABLED_FEATURES {
            command.args(["--disable", feature]);
        }
        for setting in CONFIG_OVERRIDES {
            command.args(["-c", setting]);
        }
        for feature in disabled_features(spec) {
            command.args(["--disable", feature]);
        }
        for setting in runtime_config(spec) {
            command.args(["-c", &setting]);
        }
        let catalog_setting = format!(
            "model_catalog_json={}",
            serde_json::to_string(&catalog_path.display().to_string()).map_err(|error| {
                CodexError::Protocol(format!("could not encode model catalog path: {error}"))
            })?
        );
        command
            .args(["-c", &catalog_setting, "app-server", "--stdio"])
            .current_dir(effective_cwd)
            .env("CODEX_HOME", codex_home)
            .env_remove("CODEX_EXEC_SERVER_URL")
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .kill_on_drop(true);
        command.as_std_mut().process_group(0);
        Ok(command)
    }
}

struct ProtocolClient {
    stdin: ChildStdin,
    lines: mpsc::Receiver<io::Result<Vec<u8>>>,
    events: mpsc::Sender<CodexEvent>,
    next_request_id: i64,
    final_message: String,
    active_thread_id: Option<String>,
    active_turn_id: Option<String>,
    allowed_tools: BTreeSet<String>,
    seen_tool_calls: BTreeSet<String>,
}

impl ProtocolClient {
    async fn run(
        mut self,
        spec: &CodexRunSpec,
        effective_cwd: &Path,
    ) -> Result<CodexOutcome, CodexError> {
        self.request(
            "initialize",
            json!({
                "clientInfo": {
                    "name": "nucleus",
                    "title": "Nucleus",
                    "version": env!("CARGO_PKG_VERSION")
                },
                "capabilities": { "experimentalApi": true }
            }),
        )
        .await?;
        self.notify("initialized", None).await?;
        self.ensure_no_mcp_servers().await?;

        let dynamic_tools = dynamic_tool_specs(&spec.tools);
        let sandbox = match spec.workspace_access {
            WorkspaceAccess::None | WorkspaceAccess::ReadOnly => "read-only",
            WorkspaceAccess::ReadWrite => "workspace-write",
        };
        let thread = self
            .request(
                "thread/start",
                json!({
                    "model": spec.model,
                    "cwd": effective_cwd.display().to_string(),
                    "approvalPolicy": "never",
                    "sandbox": sandbox,
                    "baseInstructions": spec.instructions,
                    "ephemeral": true,
                    "dynamicTools": dynamic_tools
                }),
            )
            .await?;
        let thread_id = required_string(&thread, "/thread/id", "thread/start response")?;
        self.active_thread_id = Some(thread_id.clone());
        let mut turn_params = json!({
            "threadId": thread_id,
            "input": [{ "type": "text", "text": spec.prompt, "textElements": [] }]
        });
        if let Some(effort) = &spec.reasoning_effort {
            turn_params["effort"] = json!(effort);
        }
        let turn = self.request("turn/start", turn_params).await?;
        let turn_id = required_string(&turn, "/turn/id", "turn/start response")?;
        self.active_turn_id = Some(turn_id.clone());

        loop {
            let message = self.receive().await?;
            if self.handle_server_request(&message).await? {
                continue;
            }
            self.record_agent_message(&message);
            if message.get("method").and_then(Value::as_str) != Some("turn/completed") {
                continue;
            }
            if message.pointer("/params/threadId").and_then(Value::as_str)
                != Some(thread_id.as_str())
                || message.pointer("/params/turn/id").and_then(Value::as_str)
                    != Some(turn_id.as_str())
            {
                continue;
            }
            let Some(status) = message
                .pointer("/params/turn/status")
                .and_then(Value::as_str)
            else {
                return Err(CodexError::Protocol(
                    "turn/completed omitted turn status".to_owned(),
                ));
            };
            if status == "completed" {
                return Ok(CodexOutcome {
                    thread_id,
                    turn_id,
                    final_message: self.final_message,
                });
            }
            let detail = message
                .pointer("/params/turn/error/message")
                .and_then(Value::as_str)
                .unwrap_or("no error detail was provided")
                .to_owned();
            return Err(CodexError::TurnFailed {
                status: status.to_owned(),
                detail,
            });
        }
    }

    async fn ensure_no_mcp_servers(&mut self) -> Result<(), CodexError> {
        let response = self
            .request(
                "mcpServerStatus/list",
                json!({
                    "cursor": null,
                    "limit": null,
                    "detail": "toolsAndAuthOnly",
                    "threadId": null
                }),
            )
            .await?;
        let servers = response
            .get("data")
            .and_then(Value::as_array)
            .ok_or_else(|| {
                CodexError::Protocol("mcpServerStatus/list response omitted data".to_owned())
            })?;
        if servers.is_empty() {
            Ok(())
        } else {
            Err(CodexError::Protocol(
                "isolated app-server unexpectedly loaded an MCP server".to_owned(),
            ))
        }
    }

    async fn request(&mut self, method: &str, params: Value) -> Result<Value, CodexError> {
        let id = self.next_request_id;
        self.next_request_id += 1;
        self.write(&json!({
            "jsonrpc": "2.0",
            "id": id,
            "method": method,
            "params": params
        }))
        .await?;
        loop {
            let message = self.receive().await?;
            if self.handle_server_request(&message).await? {
                continue;
            }
            self.record_agent_message(&message);
            if message.get("id") != Some(&json!(id)) {
                continue;
            }
            if let Some(error) = message.get("error") {
                let detail = error
                    .get("message")
                    .and_then(Value::as_str)
                    .unwrap_or("unknown JSON-RPC error");
                return Err(CodexError::Protocol(format!("{method} failed: {detail}")));
            }
            return message
                .get("result")
                .cloned()
                .ok_or_else(|| CodexError::Protocol(format!("{method} response omitted result")));
        }
    }

    async fn notify(&mut self, method: &str, params: Option<Value>) -> Result<(), CodexError> {
        let mut message = json!({ "jsonrpc": "2.0", "method": method });
        if let Some(params) = params {
            message["params"] = params;
        }
        self.write(&message).await
    }

    async fn receive(&mut self) -> Result<Value, CodexError> {
        let bytes = self
            .lines
            .recv()
            .await
            .ok_or_else(|| CodexError::Protocol("app-server stdout closed".to_owned()))?
            .map_err(|error| CodexError::Protocol(error.to_string()))?;
        serde_json::from_slice(&bytes).map_err(|error| {
            CodexError::Protocol(format!("app-server emitted invalid JSON-RPC: {error}"))
        })
    }

    async fn write(&mut self, message: &Value) -> Result<(), CodexError> {
        let mut bytes = serde_json::to_vec(message)
            .map_err(|error| CodexError::Protocol(format!("could not encode JSON-RPC: {error}")))?;
        bytes.push(b'\n');
        self.events
            .send(CodexEvent::Protocol {
                direction: ProtocolDirection::ToHarness,
                bytes: bytes.clone(),
            })
            .await
            .map_err(|_| CodexError::EventConsumerDisconnected)?;
        self.stdin
            .write_all(&bytes)
            .await
            .map_err(|error| CodexError::Protocol(format!("could not write JSON-RPC: {error}")))?;
        self.stdin
            .flush()
            .await
            .map_err(|error| CodexError::Protocol(format!("could not flush JSON-RPC: {error}")))
    }

    async fn handle_server_request(&mut self, message: &Value) -> Result<bool, CodexError> {
        let Some(method) = message.get("method").and_then(Value::as_str) else {
            return Ok(false);
        };
        let Some(id) = message.get("id").cloned() else {
            return Ok(false);
        };
        if method != "item/tool/call" {
            self.write(&json!({
                "jsonrpc": "2.0",
                "id": id,
                "error": { "code": -32601, "message": format!("unsupported server request {method:?}") }
            }))
            .await?;
            return Err(CodexError::Protocol(format!(
                "app-server requested unsupported operation {method:?}"
            )));
        }

        let params = message.get("params").cloned().unwrap_or_else(|| json!({}));
        if params
            .get("namespace")
            .is_some_and(|value| !value.is_null())
        {
            return Err(CodexError::Protocol(
                "dynamic tool call unexpectedly included a namespace".to_owned(),
            ));
        }
        let call_id = required_string(&params, "/callId", "tool call")?;
        let name = required_string(&params, "/tool", "tool call")?;
        let thread_id = required_string(&params, "/threadId", "tool call")?;
        let turn_id = required_string(&params, "/turnId", "tool call")?;
        if self.active_thread_id.as_deref() != Some(thread_id.as_str())
            || self.active_turn_id.as_deref() != Some(turn_id.as_str())
        {
            return Err(CodexError::Protocol(
                "dynamic tool call did not belong to the active thread and turn".to_owned(),
            ));
        }
        if !self.allowed_tools.contains(&name) {
            return Err(CodexError::Protocol(format!(
                "app-server requested undeclared dynamic tool {name:?}"
            )));
        }
        if !self.seen_tool_calls.insert(call_id.clone()) {
            return Err(CodexError::Protocol(format!(
                "app-server repeated dynamic tool call id {call_id:?}"
            )));
        }
        let arguments = params
            .get("arguments")
            .cloned()
            .ok_or_else(|| CodexError::Protocol("tool call omitted arguments".to_owned()))?;
        if !arguments.is_object() {
            return Err(CodexError::Protocol(
                "tool call arguments were not an object".to_owned(),
            ));
        }
        let (reply, result) = oneshot::channel();
        self.events
            .send(CodexEvent::ToolCall(PendingToolCall {
                call_id,
                name,
                arguments,
                reply,
            }))
            .await
            .map_err(|_| CodexError::EventConsumerDisconnected)?;
        let result = result.await.map_err(|_| {
            CodexError::Protocol("tool call result producer disconnected".to_owned())
        })?;
        self.write(&json!({
            "jsonrpc": "2.0",
            "id": id,
            "result": {
                "contentItems": [{ "type": "inputText", "text": result.content }],
                "success": result.success
            }
        }))
        .await?;
        Ok(true)
    }

    fn record_agent_message(&mut self, message: &Value) {
        let item = match message.get("method").and_then(Value::as_str) {
            Some("item/completed") => message.pointer("/params/item"),
            Some("turn/completed") => message
                .pointer("/params/turn/items")
                .and_then(Value::as_array)
                .and_then(|items| {
                    items.iter().rev().find(|item| {
                        item.get("type").and_then(Value::as_str) == Some("agentMessage")
                    })
                }),
            _ => None,
        };
        if let Some(text) = item
            .filter(|item| item.get("type").and_then(Value::as_str) == Some("agentMessage"))
            .and_then(|item| item.get("text"))
            .and_then(Value::as_str)
        {
            text.clone_into(&mut self.final_message);
        }
    }
}

#[allow(clippy::too_many_lines)]
fn verify_protocol_semantics(document: &Value) -> Result<(), CodexError> {
    for (definition, method, params_ref) in [
        (
            "ClientRequest",
            "initialize",
            "#/definitions/InitializeParams",
        ),
        (
            "ClientRequest",
            "thread/start",
            "#/definitions/v2/ThreadStartParams",
        ),
        (
            "ClientRequest",
            "turn/start",
            "#/definitions/v2/TurnStartParams",
        ),
        (
            "ClientRequest",
            "mcpServerStatus/list",
            "#/definitions/v2/ListMcpServerStatusParams",
        ),
        (
            "ServerRequest",
            "item/tool/call",
            "#/definitions/DynamicToolCallParams",
        ),
        (
            "ServerNotification",
            "item/completed",
            "#/definitions/v2/ItemCompletedNotification",
        ),
        (
            "ServerNotification",
            "turn/completed",
            "#/definitions/v2/TurnCompletedNotification",
        ),
    ] {
        require_method(document, definition, method, params_ref)?;
    }

    let thread_start = protocol_definition(document, &["v2", "ThreadStartParams"])?;
    require_properties(
        thread_start,
        "v2/ThreadStartParams",
        &[
            "approvalPolicy",
            "baseInstructions",
            "cwd",
            "dynamicTools",
            "ephemeral",
            "model",
            "sandbox",
        ],
    )?;
    require_enum_value(
        protocol_definition(document, &["v2", "AskForApproval"])?,
        "v2/AskForApproval",
        "never",
    )?;
    let sandbox = protocol_definition(document, &["v2", "SandboxMode"])?;
    require_enum_value(sandbox, "v2/SandboxMode", "read-only")?;
    require_enum_value(sandbox, "v2/SandboxMode", "workspace-write")?;

    let turn_start = protocol_definition(document, &["v2", "TurnStartParams"])?;
    require_properties(
        turn_start,
        "v2/TurnStartParams",
        &["effort", "input", "threadId"],
    )?;
    require_required(turn_start, "v2/TurnStartParams", &["input", "threadId"])?;

    let dynamic_tool = protocol_definition(document, &["v2", "DynamicToolSpec"])?;
    let function_tool = dynamic_tool
        .get("oneOf")
        .and_then(Value::as_array)
        .and_then(|variants| {
            variants.iter().find(|variant| {
                contains_enum_value(
                    variant.pointer("/properties/type").unwrap_or(&Value::Null),
                    "function",
                )
            })
        })
        .ok_or_else(|| {
            incompatible_protocol("v2/DynamicToolSpec omitted the function tool variant")
        })?;
    require_required(
        function_tool,
        "v2/DynamicToolSpec function variant",
        &["description", "inputSchema", "name", "type"],
    )?;

    require_required(
        protocol_definition(document, &["DynamicToolCallParams"])?,
        "DynamicToolCallParams",
        &["arguments", "callId", "threadId", "tool", "turnId"],
    )?;
    require_required(
        protocol_definition(document, &["v2", "ThreadStartResponse"])?,
        "v2/ThreadStartResponse",
        &["thread"],
    )?;
    require_required(
        protocol_definition(document, &["v2", "TurnStartResponse"])?,
        "v2/TurnStartResponse",
        &["turn"],
    )?;
    require_required(
        protocol_definition(document, &["v2", "Thread"])?,
        "v2/Thread",
        &["id"],
    )?;
    require_required(
        protocol_definition(document, &["v2", "Turn"])?,
        "v2/Turn",
        &["id", "status"],
    )?;
    require_enum_value(
        protocol_definition(document, &["v2", "TurnStatus"])?,
        "v2/TurnStatus",
        "completed",
    )?;
    require_required(
        protocol_definition(document, &["v2", "ItemCompletedNotification"])?,
        "v2/ItemCompletedNotification",
        &["item", "threadId", "turnId"],
    )?;
    require_required(
        protocol_definition(document, &["v2", "TurnCompletedNotification"])?,
        "v2/TurnCompletedNotification",
        &["threadId", "turn"],
    )
}

fn protocol_definition<'a>(document: &'a Value, path: &[&str]) -> Result<&'a Value, CodexError> {
    let mut value = document
        .get("definitions")
        .ok_or_else(|| incompatible_protocol("generated schema omitted the definitions object"))?;
    for segment in path {
        value = value.get(*segment).ok_or_else(|| {
            incompatible_protocol(format!(
                "generated schema omitted definition {}",
                path.join("/")
            ))
        })?;
    }
    Ok(value)
}

fn require_method(
    document: &Value,
    definition: &str,
    method: &str,
    params_ref: &str,
) -> Result<(), CodexError> {
    let variants = protocol_definition(document, &[definition])?
        .get("oneOf")
        .and_then(Value::as_array)
        .ok_or_else(|| incompatible_protocol(format!("{definition} omitted oneOf")))?;
    let variant = variants
        .iter()
        .find(|variant| {
            variant
                .pointer("/properties/method/enum")
                .and_then(Value::as_array)
                .is_some_and(|values| values.iter().any(|value| value.as_str() == Some(method)))
        })
        .ok_or_else(|| incompatible_protocol(format!("{definition} omitted method {method}")))?;
    let found_ref = variant
        .pointer("/properties/params/$ref")
        .and_then(Value::as_str);
    if found_ref == Some(params_ref) {
        Ok(())
    } else {
        Err(incompatible_protocol(format!(
            "{definition} method {method} parameters must reference {params_ref}"
        )))
    }
}

fn require_properties(definition: &Value, name: &str, fields: &[&str]) -> Result<(), CodexError> {
    let properties = definition
        .get("properties")
        .and_then(Value::as_object)
        .ok_or_else(|| incompatible_protocol(format!("{name} omitted properties")))?;
    for field in fields {
        if !properties.contains_key(*field) {
            return Err(incompatible_protocol(format!(
                "{name} omitted property {field}"
            )));
        }
    }
    Ok(())
}

fn require_required(definition: &Value, name: &str, fields: &[&str]) -> Result<(), CodexError> {
    let required = definition
        .get("required")
        .and_then(Value::as_array)
        .ok_or_else(|| incompatible_protocol(format!("{name} omitted required")))?;
    for field in fields {
        if !required
            .iter()
            .any(|required_field| required_field.as_str() == Some(field))
        {
            return Err(incompatible_protocol(format!(
                "{name} does not require {field}"
            )));
        }
    }
    Ok(())
}

fn require_enum_value(definition: &Value, name: &str, value: &str) -> Result<(), CodexError> {
    if contains_enum_value(definition, value) {
        Ok(())
    } else {
        Err(incompatible_protocol(format!(
            "{name} omitted enum value {value}"
        )))
    }
}

fn contains_enum_value(value: &Value, expected: &str) -> bool {
    match value {
        Value::Array(values) => values
            .iter()
            .any(|value| contains_enum_value(value, expected)),
        Value::Object(object) => {
            object
                .get("enum")
                .and_then(Value::as_array)
                .is_some_and(|values| values.iter().any(|value| value.as_str() == Some(expected)))
                || object
                    .values()
                    .any(|value| contains_enum_value(value, expected))
        }
        _ => false,
    }
}

fn incompatible_protocol(reason: impl Into<String>) -> CodexError {
    unsupported("harness.protocolSchema", reason)
}

fn validate_tools(tools: &[DynamicTool]) -> Result<(), CodexError> {
    let mut names = BTreeSet::new();
    for tool in tools {
        if tool.name.is_empty()
            || tool.name.len() > 128
            || !tool
                .name
                .bytes()
                .all(|byte| byte.is_ascii_alphanumeric() || byte == b'_' || byte == b'-')
        {
            return Err(unsupported(
                "toolset",
                format!("tool name {:?} is invalid", tool.name),
            ));
        }
        if !names.insert(&tool.name) {
            return Err(unsupported(
                "toolset",
                format!("tool name {:?} is duplicated", tool.name),
            ));
        }
        if tool.description.is_empty() {
            return Err(unsupported(
                "toolset",
                format!("tool {:?} has no description", tool.name),
            ));
        }
        if !tool.input_schema.is_object() {
            return Err(unsupported(
                "toolset",
                format!("tool {:?} input schema is not an object", tool.name),
            ));
        }
    }
    Ok(())
}

fn dynamic_tool_specs(tools: &[DynamicTool]) -> Vec<Value> {
    tools
        .iter()
        .map(|tool| {
            json!({
                "type": "function",
                "name": tool.name,
                "description": tool.description,
                "inputSchema": tool.input_schema,
                "deferLoading": false
            })
        })
        .collect()
}

fn disabled_features(spec: &CodexRunSpec) -> Vec<&'static str> {
    let mut features = Vec::new();
    if !spec.builtin_tools.local_execution {
        features.extend(["code_mode", "code_mode_host", "code_mode_only"]);
    }
    if !spec.builtin_tools.web_search {
        features.push("standalone_web_search");
    }
    features
}

fn runtime_config(spec: &CodexRunSpec) -> Vec<String> {
    let local = spec.builtin_tools.local_execution;
    let mut settings = vec![
        format!("include_environment_context={local}"),
        format!("include_permissions_instructions={local}"),
        if spec.builtin_tools.web_search {
            "web_search=\"live\"".to_owned()
        } else {
            "web_search=\"disabled\"".to_owned()
        },
    ];
    if local {
        settings.push("features.code_mode_host=true".to_owned());
        settings.push("shell_environment_policy.inherit=\"all\"".to_owned());
        if matches!(spec.workspace_access, WorkspaceAccess::ReadOnly) {
            settings.push("sandbox_permissions=[\"disk-full-read-access\"]".to_owned());
        }
    }
    settings
}

fn configured_model_catalog(bytes: &[u8], spec: &CodexRunSpec) -> Result<Value, CodexError> {
    let mut catalog: Value = serde_json::from_slice(bytes)
        .map_err(|error| CodexError::Inspection(format!("invalid model catalog: {error}")))?;
    let models = catalog
        .get_mut("models")
        .and_then(Value::as_array_mut)
        .ok_or_else(|| CodexError::Inspection("model catalog omitted models".to_owned()))?;
    let index = models
        .iter()
        .position(|model| model.get("slug").and_then(Value::as_str) == Some(spec.model.as_str()))
        .ok_or_else(|| {
            unsupported(
                "model",
                format!("{} is not in the bundled model catalog", spec.model),
            )
        })?;
    let mut model = models.remove(index);
    let object = model.as_object_mut().ok_or_else(|| {
        CodexError::Inspection(format!("the {} catalog entry is not an object", spec.model))
    })?;
    let supports_local_execution = object
        .get("shell_type")
        .and_then(Value::as_str)
        .is_some_and(|kind| kind != "disabled");
    if spec.builtin_tools.local_execution && !supports_local_execution {
        return Err(unsupported(
            "builtinTools.localExecution",
            format!("{} does not support local execution", spec.model),
        ));
    }
    let supports_web_search = object
        .get("supports_search_tool")
        .and_then(Value::as_bool)
        .unwrap_or(false);
    if spec.builtin_tools.web_search && !supports_web_search {
        return Err(unsupported(
            "builtinTools.webSearch",
            format!("{} does not support web search", spec.model),
        ));
    }

    object.insert("multi_agent_version".to_owned(), json!("disabled"));
    object.insert("supports_parallel_tool_calls".to_owned(), json!(false));
    object.insert("include_skills_usage_instructions".to_owned(), json!(false));
    object.insert("experimental_supported_tools".to_owned(), json!([]));
    object.insert("input_modalities".to_owned(), json!(["text"]));
    object.insert("base_instructions".to_owned(), json!(spec.instructions));
    object.insert("model_messages".to_owned(), Value::Null);
    if !spec.builtin_tools.local_execution {
        object.insert("tool_mode".to_owned(), json!("direct"));
        object.insert("shell_type".to_owned(), json!("disabled"));
    }
    if !spec.builtin_tools.web_search {
        object.insert("supports_search_tool".to_owned(), json!(false));
    }
    if !(spec.builtin_tools.local_execution
        && matches!(spec.workspace_access, WorkspaceAccess::ReadWrite))
    {
        object.insert("apply_patch_tool_type".to_owned(), Value::Null);
    }
    *models = vec![model];
    Ok(catalog)
}

async fn read_protocol_lines(
    stdout: tokio::process::ChildStdout,
    sender: mpsc::Sender<io::Result<Vec<u8>>>,
    events: mpsc::Sender<CodexEvent>,
) -> Result<(), CodexError> {
    let mut reader = BufReader::new(stdout);
    let mut total = 0_u64;
    let mut protocol_consumer_connected = true;
    loop {
        let mut line = Vec::new();
        let count = reader
            .read_until(b'\n', &mut line)
            .await
            .map_err(|error| CodexError::Protocol(error.to_string()))?;
        if count == 0 {
            return Ok(());
        }
        total = total.saturating_add(count as u64);
        events
            .send(CodexEvent::Protocol {
                direction: ProtocolDirection::FromHarness,
                bytes: line.clone(),
            })
            .await
            .map_err(|_| CodexError::EventConsumerDisconnected)?;
        if total > MAX_PROTOCOL_BYTES {
            let _ = sender
                .send(Err(io::Error::other(
                    "app-server exceeded the protocol output limit",
                )))
                .await;
            return Ok(());
        }
        if protocol_consumer_connected && sender.send(Ok(line)).await.is_err() {
            protocol_consumer_connected = false;
        }
    }
}

async fn read_stderr(
    mut stderr: tokio::process::ChildStderr,
    sender: mpsc::Sender<CodexEvent>,
) -> Result<(), CodexError> {
    let mut buffer = vec![0_u8; STDERR_CHUNK_BYTES];
    loop {
        let count = stderr
            .read(&mut buffer)
            .await
            .map_err(|error| CodexError::Protocol(format!("could not read stderr: {error}")))?;
        if count == 0 {
            return Ok(());
        }
        sender
            .send(CodexEvent::Stderr(buffer[..count].to_vec()))
            .await
            .map_err(|_| CodexError::EventConsumerDisconnected)?;
    }
}

async fn wait_for_cancellation(cancelled: &mut watch::Receiver<bool>) {
    loop {
        if *cancelled.borrow() {
            return;
        }
        if cancelled.changed().await.is_err() {
            // Losing the producer is not a cancellation request. Continue to
            // rely on the harness result and the wall-clock deadline.
            future::pending::<()>().await;
        }
    }
}

async fn terminate_process_group(child: &mut Child, guard: &mut ProcessGroupGuard) {
    if let Some(group) = guard.group {
        signal_process_group(group, "-TERM").await;
    } else {
        let _ = child.start_kill();
    }
    let needs_wait = !matches!(
        tokio::time::timeout(SHUTDOWN_GRACE, child.wait()).await,
        Ok(Ok(_))
    );
    // The direct child can exit while a grandchild ignores TERM, so signal the
    // full group once more before disarming the drop guard.
    if let Some(group) = guard.group {
        signal_process_group(group, "-KILL").await;
    }
    if needs_wait {
        let _ = child.start_kill();
        let _ = child.wait().await;
    }
    guard.disarm();
}

async fn signal_process_group(group: u32, signal: &str) {
    let _ = Command::new("/bin/kill")
        .args([OsStr::new(signal), OsStr::new("--")])
        .arg(format!("-{group}"))
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .await;
}

/// Last-resort cleanup when an async run is dropped or aborted.
struct ProcessGroupGuard {
    group: Option<u32>,
    armed: bool,
}

impl ProcessGroupGuard {
    const fn new(group: Option<u32>) -> Self {
        Self { group, armed: true }
    }

    const fn disarm(&mut self) {
        self.armed = false;
    }
}

impl Drop for ProcessGroupGuard {
    fn drop(&mut self) {
        let Some(group) = self.group.filter(|_| self.armed) else {
            return;
        };
        let _ = StdCommand::new("/bin/kill")
            .args([OsStr::new("-KILL"), OsStr::new("--")])
            .arg(format!("-{group}"))
            .stdin(Stdio::null())
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .status();
    }
}

async fn join_reader(
    task: JoinHandle<Result<(), CodexError>>,
    stream: &str,
) -> Result<(), CodexError> {
    task.await
        .map_err(|error| CodexError::Protocol(format!("{stream} reader task failed: {error}")))?
}

async fn copy_codex_auth(isolated_home: &Path) -> Result<(), CodexError> {
    let source_home = std::env::var_os("CODEX_HOME")
        .filter(|value| !value.is_empty())
        .map(PathBuf::from)
        .or_else(|| {
            std::env::var_os("HOME")
                .filter(|value| !value.is_empty())
                .map(|home| PathBuf::from(home).join(".codex"))
        });
    let Some(source) = source_home.map(|home| home.join("auth.json")) else {
        return Ok(());
    };
    if !source.is_file() {
        return Ok(());
    }
    let bytes = tokio::fs::read(source)
        .await
        .map_err(CodexError::Preparation)?;
    let destination = isolated_home.join("auth.json");
    let mut options = tokio::fs::OpenOptions::new();
    options.write(true).create_new(true).mode(0o600);
    let mut file = options
        .open(destination)
        .await
        .map_err(CodexError::Preparation)?;
    file.write_all(&bytes)
        .await
        .map_err(CodexError::Preparation)?;
    file.flush().await.map_err(CodexError::Preparation)
}

fn required_string(value: &Value, pointer: &str, context: &str) -> Result<String, CodexError> {
    value
        .pointer(pointer)
        .and_then(Value::as_str)
        .map(str::to_owned)
        .ok_or_else(|| CodexError::Protocol(format!("{context} omitted {pointer}")))
}

fn unsupported(setting: &str, reason: impl Into<String>) -> CodexError {
    CodexError::UnsupportedSetting {
        setting: setting.to_owned(),
        reason: reason.into(),
    }
}

fn diagnostic(prefix: &str, stderr: &[u8]) -> String {
    let detail = String::from_utf8_lossy(stderr);
    let detail = detail.trim();
    if detail.is_empty() {
        prefix.to_owned()
    } else {
        format!("{prefix}: {detail}")
    }
}

#[cfg(test)]
mod tests {
    use super::{
        BuiltinToolsV1, CodexEvent, CodexHarness, CodexRunSpec, DynamicTool, GeneratedSchema,
        HarnessInspection, ModelCapability, SUPPORTED_CODEX_VERSION, ToolResult, WorkspaceAccess,
        configured_model_catalog, disabled_features, dynamic_tool_specs, runtime_config,
    };
    use serde_json::{Value, json};
    use std::fs;
    use std::os::unix::fs::PermissionsExt as _;
    use std::path::Path;
    use std::process::{Command, Stdio};
    use std::time::Duration;
    use tokio::sync::{mpsc, watch};

    fn inspection() -> HarnessInspection {
        HarnessInspection {
            harness: "codex".to_owned(),
            version: SUPPORTED_CODEX_VERSION.to_owned(),
            executable: "codex".into(),
            models: vec![ModelCapability {
                model: "example-model".to_owned(),
                default_reasoning_effort: Some("medium".to_owned()),
                reasoning_efforts: vec!["medium".to_owned()],
                supports_local_execution: true,
                supports_web_search: true,
            }],
        }
    }

    fn method_schema(method: &str, params_ref: &str) -> Value {
        json!({
            "properties": {
                "method": { "enum": [method] },
                "params": { "$ref": params_ref }
            }
        })
    }

    fn compatible_protocol_schema() -> GeneratedSchema {
        let document = json!({
            "definitions": {
                "ClientRequest": { "oneOf": [
                    method_schema("initialize", "#/definitions/InitializeParams"),
                    method_schema("thread/start", "#/definitions/v2/ThreadStartParams"),
                    method_schema("turn/start", "#/definitions/v2/TurnStartParams"),
                    method_schema(
                        "mcpServerStatus/list",
                        "#/definitions/v2/ListMcpServerStatusParams"
                    )
                ] },
                "ServerRequest": { "oneOf": [
                    method_schema("item/tool/call", "#/definitions/DynamicToolCallParams")
                ] },
                "ServerNotification": { "oneOf": [
                    method_schema(
                        "item/completed",
                        "#/definitions/v2/ItemCompletedNotification"
                    ),
                    method_schema(
                        "turn/completed",
                        "#/definitions/v2/TurnCompletedNotification"
                    )
                ] },
                "DynamicToolCallParams": {
                    "required": ["arguments", "callId", "threadId", "tool", "turnId"]
                },
                "v2": {
                    "ThreadStartParams": { "properties": {
                        "approvalPolicy": {}, "baseInstructions": {}, "cwd": {}, "dynamicTools": {},
                        "ephemeral": {}, "model": {}, "sandbox": {}
                    } },
                    "AskForApproval": { "enum": ["never"] },
                    "SandboxMode": { "enum": ["read-only", "workspace-write"] },
                    "TurnStartParams": {
                        "required": ["input", "threadId"],
                        "properties": { "effort": {}, "input": {}, "threadId": {} }
                    },
                    "DynamicToolSpec": { "oneOf": [{
                        "required": ["description", "inputSchema", "name", "type"],
                        "properties": { "type": { "enum": ["function"] } }
                    }] },
                    "ThreadStartResponse": { "required": ["thread"] },
                    "TurnStartResponse": { "required": ["turn"] },
                    "Thread": { "required": ["id"] },
                    "Turn": { "required": ["id", "status"] },
                    "TurnStatus": { "enum": ["completed", "failed"] },
                    "ItemCompletedNotification": {
                        "required": ["item", "threadId", "turnId"]
                    },
                    "TurnCompletedNotification": { "required": ["threadId", "turn"] }
                }
            }
        });
        GeneratedSchema {
            media_type: "application/schema+json",
            bytes: serde_json::to_vec(&document)
                .unwrap_or_else(|error| panic!("encode compatible protocol schema: {error}")),
        }
    }

    #[test]
    fn validation_is_against_inspected_capabilities() {
        let directory = tempfile::tempdir()
            .unwrap_or_else(|error| panic!("create temporary directory: {error}"));
        let mut spec = CodexRunSpec {
            instructions: "Follow the requester contract.".to_owned(),
            prompt: "work".to_owned(),
            model: "example-model".to_owned(),
            reasoning_effort: Some("medium".to_owned()),
            working_directory: directory.path().to_path_buf(),
            workspace_access: WorkspaceAccess::ReadOnly,
            builtin_tools: BuiltinToolsV1 {
                local_execution: false,
                web_search: false,
            },
            timeout: Duration::from_secs(30),
            tools: Vec::new(),
        };
        let harness = CodexHarness::new("codex");
        harness
            .validate(&inspection(), &spec)
            .unwrap_or_else(|error| panic!("validate supported invocation: {error}"));
        spec.reasoning_effort = Some("ultra".to_owned());
        let error = match harness.validate(&inspection(), &spec) {
            Ok(()) => panic!("unsupported reasoning effort must fail validation"),
            Err(error) => error,
        };
        assert!(error.to_string().contains("reasoningEffort"));

        let mut unknown_version = inspection();
        unknown_version.version = "0.147.0".to_owned();
        let error = match harness.validate(&unknown_version, &spec) {
            Ok(()) => panic!("unknown Codex version must fail validation"),
            Err(error) => error,
        };
        assert!(error.to_string().contains("harness.version"));
        assert!(error.to_string().contains(SUPPORTED_CODEX_VERSION));
    }

    #[test]
    fn protocol_schema_is_bound_to_required_v1_semantics() {
        let harness = CodexHarness::new("codex");
        let schema = compatible_protocol_schema();
        harness
            .validate_protocol_schema(&inspection(), &schema)
            .unwrap_or_else(|error| panic!("validate supported protocol schema: {error}"));

        let mut incompatible: Value = serde_json::from_slice(&schema.bytes)
            .unwrap_or_else(|error| panic!("decode protocol schema: {error}"));
        incompatible
            .pointer_mut("/definitions/v2/ThreadStartParams/properties")
            .and_then(Value::as_object_mut)
            .unwrap_or_else(|| panic!("protocol schema must contain thread start properties"))
            .remove("dynamicTools");
        let incompatible = GeneratedSchema {
            media_type: "application/schema+json",
            bytes: serde_json::to_vec(&incompatible)
                .unwrap_or_else(|error| panic!("encode incompatible schema: {error}")),
        };
        let error = match harness.validate_protocol_schema(&inspection(), &incompatible) {
            Ok(()) => panic!("schema without dynamic tools must fail validation"),
            Err(error) => error,
        };
        assert!(error.to_string().contains("harness.protocolSchema"));
        assert!(error.to_string().contains("dynamicTools"));
    }

    #[test]
    fn tools_translate_to_codex_without_exposing_argv() {
        let tools = dynamic_tool_specs(&[DynamicTool {
            name: "create_todo".to_owned(),
            description: "Create one todo".to_owned(),
            input_schema: json!({"type": "object"}),
        }]);
        assert_eq!(tools[0]["type"], "function");
        assert_eq!(tools[0]["name"], "create_todo");
        assert_eq!(tools[0]["deferLoading"], false);
    }

    #[test]
    fn catalog_enforces_each_builtin_tool_setting() {
        let bytes = serde_json::to_vec(&json!({
            "models": [{
                "slug": "example-model",
                "tool_mode": "code_mode_only",
                "shell_type": "shell_command",
                "supports_search_tool": true,
                "apply_patch_tool_type": "freeform",
                "multi_agent_version": "v2"
            }, { "slug": "other-model" }]
        }))
        .unwrap_or_else(|error| panic!("encode catalog: {error}"));
        let directory = tempfile::tempdir()
            .unwrap_or_else(|error| panic!("create temporary directory: {error}"));
        let mut spec = CodexRunSpec {
            instructions: "Follow the requester contract.".to_owned(),
            prompt: "work".to_owned(),
            model: "example-model".to_owned(),
            reasoning_effort: Some("medium".to_owned()),
            working_directory: directory.path().to_path_buf(),
            workspace_access: WorkspaceAccess::ReadOnly,
            builtin_tools: BuiltinToolsV1 {
                local_execution: false,
                web_search: false,
            },
            timeout: Duration::from_secs(30),
            tools: Vec::new(),
        };

        let restricted = configured_model_catalog(&bytes, &spec)
            .unwrap_or_else(|error| panic!("configure restricted catalog: {error}"));
        let model = &restricted["models"][0];
        assert_eq!(restricted["models"].as_array().map(Vec::len), Some(1));
        assert_eq!(model["tool_mode"], "direct");
        assert_eq!(model["shell_type"], "disabled");
        assert_eq!(model["supports_search_tool"], false);
        assert!(model["apply_patch_tool_type"].is_null());
        assert_eq!(model["multi_agent_version"], "disabled");
        assert_eq!(
            model["base_instructions"].as_str(),
            Some(spec.instructions.as_str())
        );
        assert!(model["model_messages"].is_null());

        spec.builtin_tools = BuiltinToolsV1 {
            local_execution: true,
            web_search: true,
        };
        spec.workspace_access = WorkspaceAccess::ReadWrite;
        let enabled = configured_model_catalog(&bytes, &spec)
            .unwrap_or_else(|error| panic!("configure enabled catalog: {error}"));
        let model = &enabled["models"][0];
        assert_eq!(model["tool_mode"], "code_mode_only");
        assert_eq!(model["shell_type"], "shell_command");
        assert_eq!(model["supports_search_tool"], true);
        assert_eq!(model["apply_patch_tool_type"], "freeform");
    }

    #[test]
    fn runtime_flags_are_derived_from_builtin_tool_policy() {
        let directory = tempfile::tempdir()
            .unwrap_or_else(|error| panic!("create temporary directory: {error}"));
        let mut spec = CodexRunSpec {
            instructions: "Follow the requester contract.".to_owned(),
            prompt: "work".to_owned(),
            model: "example-model".to_owned(),
            reasoning_effort: None,
            working_directory: directory.path().to_path_buf(),
            workspace_access: WorkspaceAccess::ReadOnly,
            builtin_tools: BuiltinToolsV1 {
                local_execution: false,
                web_search: false,
            },
            timeout: Duration::from_secs(30),
            tools: Vec::new(),
        };
        assert!(disabled_features(&spec).contains(&"code_mode"));
        assert!(disabled_features(&spec).contains(&"standalone_web_search"));
        assert!(runtime_config(&spec).contains(&"web_search=\"disabled\"".to_owned()));

        spec.builtin_tools = BuiltinToolsV1 {
            local_execution: true,
            web_search: true,
        };
        assert!(!disabled_features(&spec).contains(&"code_mode"));
        assert!(!disabled_features(&spec).contains(&"standalone_web_search"));
        let settings = runtime_config(&spec);
        assert!(settings.contains(&"web_search=\"live\"".to_owned()));
        assert!(settings.contains(&"features.code_mode_host=true".to_owned()));
        assert!(settings.contains(&"sandbox_permissions=[\"disk-full-read-access\"]".to_owned()));
    }

    #[tokio::test]
    async fn fake_app_server_preserves_protocol_and_cleans_descendants()
    -> Result<(), Box<dyn std::error::Error>> {
        let directory = tempfile::tempdir()?;
        let executable = directory.path().join("fake-codex");
        let descendant_pid = directory.path().join("descendant.pid");
        write_fake_codex(&executable, &descendant_pid)?;
        let harness = CodexHarness::new(&executable);
        let inspection = harness.inspect().await?;
        assert_eq!(inspection.version, SUPPORTED_CODEX_VERSION);
        assert!(inspection.models[0].supports_local_execution);
        assert!(inspection.models[0].supports_web_search);
        let spec = CodexRunSpec {
            instructions: "Use only create_todo and call it once.".to_owned(),
            prompt: "Create one todo".to_owned(),
            model: "example-model".to_owned(),
            reasoning_effort: Some("medium".to_owned()),
            working_directory: directory.path().to_path_buf(),
            workspace_access: WorkspaceAccess::ReadOnly,
            builtin_tools: BuiltinToolsV1 {
                local_execution: false,
                web_search: false,
            },
            timeout: Duration::from_secs(5),
            tools: vec![DynamicTool {
                name: "create_todo".to_owned(),
                description: "Create one todo".to_owned(),
                input_schema: json!({"type": "object"}),
            }],
        };
        let (events_tx, mut events_rx) = mpsc::channel(32);
        let event_collector = tokio::spawn(async move {
            let mut protocol = Vec::new();
            let mut saw_stderr = false;
            while let Some(event) = events_rx.recv().await {
                match event {
                    CodexEvent::Protocol { bytes, .. } => protocol.push(bytes),
                    CodexEvent::Stderr(bytes) => saw_stderr |= !bytes.is_empty(),
                    CodexEvent::ToolCall(call) => {
                        assert_eq!(call.call_id, "call-1");
                        assert_eq!(call.name, "create_todo");
                        assert_eq!(call.arguments["title"], "Actionable");
                        call.reply
                            .send(ToolResult {
                                success: true,
                                content: r#"{"id":"t1"}"#.to_owned(),
                            })
                            .unwrap_or_else(|_| panic!("adapter must await the tool result"));
                    }
                }
            }
            (protocol, saw_stderr)
        });
        // A requester dropping the cancellation handle is not cancellation.
        let (cancel_tx, cancel_rx) = watch::channel(false);
        drop(cancel_tx);
        let outcome = harness.run(&inspection, spec, events_tx, cancel_rx).await?;
        assert_eq!(outcome.thread_id, "thread-1");
        assert_eq!(outcome.turn_id, "turn-1");
        assert_eq!(outcome.final_message, "created");
        let (records, saw_stderr) = event_collector.await?;
        assert!(saw_stderr);
        assert!(records.iter().all(|record| record.ends_with(b"\n")));
        assert!(records.iter().any(|record| {
            std::str::from_utf8(record)
                .is_ok_and(|line| line.contains("\"method\":\"item/tool/call\""))
        }));
        assert!(records.iter().any(|record| {
            std::str::from_utf8(record).is_ok_and(|line| {
                line.contains("\"baseInstructions\":\"Use only create_todo and call it once.\"")
            })
        }));
        assert!(records.iter().any(|record| {
            std::str::from_utf8(record).is_ok_and(|line| line.contains("\\\"id\\\":\\\"t1\\\""))
        }));

        let pid: u32 = fs::read_to_string(&descendant_pid)?.trim().parse()?;
        for _ in 0..20 {
            if !process_exists(pid) {
                return Ok(());
            }
            tokio::time::sleep(Duration::from_millis(25)).await;
        }
        panic!("descendant process {pid} survived adapter cleanup");
    }

    fn write_fake_codex(path: &Path, descendant_pid: &Path) -> std::io::Result<()> {
        let script = format!(
            r#"#!/bin/sh
if [ "$1" = "--version" ]; then
  printf '%s\n' 'codex-cli 0.146.0'
  exit 0
fi
if [ "$1" = "debug" ]; then
  printf '%s\n' '{{"models":[{{"slug":"example-model","default_reasoning_level":"medium","supported_reasoning_levels":[{{"effort":"medium"}}],"tool_mode":"code_mode_only","shell_type":"shell_command","supports_search_tool":true,"apply_patch_tool_type":"freeform"}}]}}'
  exit 0
fi
case "$*" in
  *'model_catalog_json='*) ;;
  *) exit 20 ;;
esac
case "$*" in
  *'web_search="disabled"'*) ;;
  *) exit 21 ;;
esac
(trap '' TERM; sleep 300) &
printf '%s\n' "$!" > '{pidfile}'
printf '%s\n' 'diagnostic' >&2
IFS= read -r initialize
printf '%s\n' '{{"id":0,"result":{{}}}}'
IFS= read -r initialized
IFS= read -r inventory
printf '%s\n' '{{"id":1,"result":{{"data":[],"nextCursor":null}}}}'
IFS= read -r thread
printf '%s\n' '{{"id":2,"result":{{"thread":{{"id":"thread-1"}}}}}}'
IFS= read -r turn
printf '%s\n' '{{"id":3,"result":{{"turn":{{"id":"turn-1"}}}}}}'
printf '%s\n' '{{"id":20,"method":"item/tool/call","params":{{"threadId":"thread-1","turnId":"turn-1","callId":"call-1","namespace":null,"tool":"create_todo","arguments":{{"title":"Actionable"}}}}}}'
IFS= read -r tool_result
case "$tool_result" in
  *'"success":true'*) ;;
  *) exit 22 ;;
esac
printf '%s\n' '{{"method":"item/completed","params":{{"threadId":"thread-1","turnId":"turn-1","item":{{"type":"agentMessage","text":"created"}}}}}}'
printf '%s\n' '{{"method":"turn/completed","params":{{"threadId":"thread-1","turn":{{"id":"turn-1","status":"completed","items":[{{"type":"agentMessage","text":"created"}}]}}}}}}'
wait
"#,
            pidfile = descendant_pid.display(),
        );
        fs::write(path, script)?;
        let mut permissions = fs::metadata(path)?.permissions();
        permissions.set_mode(0o700);
        fs::set_permissions(path, permissions)
    }

    fn process_exists(pid: u32) -> bool {
        Command::new("/bin/kill")
            .args(["-0", "--", &pid.to_string()])
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .status()
            .is_ok_and(|status| status.success())
    }
}
