[package]
name = "conatus"
version = "0.4.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
default-run = "conatus"

[dependencies]
cell-prompts.workspace = true
chancery-usage.workspace = true
anyhow = "1"
annals = { path = "../annals/crates/annals" }
annals-api.workspace = true
cell-install.workspace = true
cell-maintenance.workspace = true
clockwork = { path = "../clockwork/crates/clockwork" }
chrono = "0.4"
email = { path = "../email/crates/email" }
clap.workspace = true
fs2.workspace = true
iatreion-api.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
toml.workspace = true
tokio.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
