#!/bin/zsh

unsetopt VERBOSE XTRACE
source "$HOME/.zshrc" >/dev/null 2>&1
unsetopt VERBOSE XTRACE

print -rn -- "${RESEND_API_KEY-}" | /usr/bin/env -i \
    HOME="$HOME" \
    PATH=/usr/bin:/bin:/usr/sbin:/sbin \
    TODO_CONFIG="$HOME/Library/Application Support/Todo/config.toml" \
    /bin/zsh -c '
IFS= read -r RESEND_API_KEY
export RESEND_API_KEY
exec "$HOME/.local/bin/todo" email send --scheduled
'
